// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sdc_internal.proto

/*
	Package sdc_internal is a generated protocol buffer package.

	It is generated from these files:
		sdc_internal.proto

	It has these top-level messages:
		ContainerMounts
		MountedFsResponse
		ContainerInfo
		MountedFsRequest
		Ping
		Pong
		DockerCommand
		DockerCommandResult
		SwarmStateCommand
		SwarmStateResult
		OrchestratorEventsStreamCommand
*/
package sdc_internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import draiosproto "cointerface/draiosproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CointerfaceMessageType int32

const (
	CointerfaceMessageType_PING                               CointerfaceMessageType = 1
	CointerfaceMessageType_PONG                               CointerfaceMessageType = 2
	CointerfaceMessageType_DOCKER_COMMAND                     CointerfaceMessageType = 3
	CointerfaceMessageType_DOCKER_COMMAND_RESULT              CointerfaceMessageType = 4
	CointerfaceMessageType_SWARM_STATE_COMMAND                CointerfaceMessageType = 5
	CointerfaceMessageType_SWARM_STATE_RESULT                 CointerfaceMessageType = 6
	CointerfaceMessageType_ORCHESTRATOR_EVENTS_STREAM_COMMAND CointerfaceMessageType = 7
	CointerfaceMessageType_ORCHESTRATOR_EVENTS_STREAM_RESULT  CointerfaceMessageType = 8
)

var CointerfaceMessageType_name = map[int32]string{
	1: "PING",
	2: "PONG",
	3: "DOCKER_COMMAND",
	4: "DOCKER_COMMAND_RESULT",
	5: "SWARM_STATE_COMMAND",
	6: "SWARM_STATE_RESULT",
	7: "ORCHESTRATOR_EVENTS_STREAM_COMMAND",
	8: "ORCHESTRATOR_EVENTS_STREAM_RESULT",
}
var CointerfaceMessageType_value = map[string]int32{
	"PING":                               1,
	"PONG":                               2,
	"DOCKER_COMMAND":                     3,
	"DOCKER_COMMAND_RESULT":              4,
	"SWARM_STATE_COMMAND":                5,
	"SWARM_STATE_RESULT":                 6,
	"ORCHESTRATOR_EVENTS_STREAM_COMMAND": 7,
	"ORCHESTRATOR_EVENTS_STREAM_RESULT":  8,
}

func (x CointerfaceMessageType) Enum() *CointerfaceMessageType {
	p := new(CointerfaceMessageType)
	*p = x
	return p
}
func (x CointerfaceMessageType) String() string {
	return proto.EnumName(CointerfaceMessageType_name, int32(x))
}
func (x *CointerfaceMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CointerfaceMessageType_value, data, "CointerfaceMessageType")
	if err != nil {
		return err
	}
	*x = CointerfaceMessageType(value)
	return nil
}
func (CointerfaceMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorSdcInternal, []int{0}
}

type DockerCmdType int32

const (
	DockerCmdType_STOP    DockerCmdType = 1
	DockerCmdType_PAUSE   DockerCmdType = 2
	DockerCmdType_UNPAUSE DockerCmdType = 3
)

var DockerCmdType_name = map[int32]string{
	1: "STOP",
	2: "PAUSE",
	3: "UNPAUSE",
}
var DockerCmdType_value = map[string]int32{
	"STOP":    1,
	"PAUSE":   2,
	"UNPAUSE": 3,
}

func (x DockerCmdType) Enum() *DockerCmdType {
	p := new(DockerCmdType)
	*p = x
	return p
}
func (x DockerCmdType) String() string {
	return proto.EnumName(DockerCmdType_name, int32(x))
}
func (x *DockerCmdType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DockerCmdType_value, data, "DockerCmdType")
	if err != nil {
		return err
	}
	*x = DockerCmdType(value)
	return nil
}
func (DockerCmdType) EnumDescriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{1} }

type ContainerMounts struct {
	ContainerId      *string                  `protobuf:"bytes,1,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	Mounts           []*draiosproto.MountedFs `protobuf:"bytes,2,rep,name=mounts" json:"mounts,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ContainerMounts) Reset()                    { *m = ContainerMounts{} }
func (m *ContainerMounts) String() string            { return proto.CompactTextString(m) }
func (*ContainerMounts) ProtoMessage()               {}
func (*ContainerMounts) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{0} }

func (m *ContainerMounts) GetContainerId() string {
	if m != nil && m.ContainerId != nil {
		return *m.ContainerId
	}
	return ""
}

func (m *ContainerMounts) GetMounts() []*draiosproto.MountedFs {
	if m != nil {
		return m.Mounts
	}
	return nil
}

type MountedFsResponse struct {
	Containers       []*ContainerMounts `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MountedFsResponse) Reset()                    { *m = MountedFsResponse{} }
func (m *MountedFsResponse) String() string            { return proto.CompactTextString(m) }
func (*MountedFsResponse) ProtoMessage()               {}
func (*MountedFsResponse) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{1} }

func (m *MountedFsResponse) GetContainers() []*ContainerMounts {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ContainerInfo struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Pid              *uint64 `protobuf:"varint,2,req,name=pid" json:"pid,omitempty"`
	Vpid             *uint64 `protobuf:"varint,3,req,name=vpid" json:"vpid,omitempty"`
	Root             *string `protobuf:"bytes,4,req,name=root" json:"root,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContainerInfo) Reset()                    { *m = ContainerInfo{} }
func (m *ContainerInfo) String() string            { return proto.CompactTextString(m) }
func (*ContainerInfo) ProtoMessage()               {}
func (*ContainerInfo) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{2} }

func (m *ContainerInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ContainerInfo) GetPid() uint64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *ContainerInfo) GetVpid() uint64 {
	if m != nil && m.Vpid != nil {
		return *m.Vpid
	}
	return 0
}

func (m *ContainerInfo) GetRoot() string {
	if m != nil && m.Root != nil {
		return *m.Root
	}
	return ""
}

type MountedFsRequest struct {
	Containers       []*ContainerInfo `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MountedFsRequest) Reset()                    { *m = MountedFsRequest{} }
func (m *MountedFsRequest) String() string            { return proto.CompactTextString(m) }
func (*MountedFsRequest) ProtoMessage()               {}
func (*MountedFsRequest) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{3} }

func (m *MountedFsRequest) GetContainers() []*ContainerInfo {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Ping struct {
	Token            *int64 `protobuf:"varint,1,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{4} }

func (m *Ping) GetToken() int64 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

type Pong struct {
	Token            *int64  `protobuf:"varint,1,req,name=token" json:"token,omitempty"`
	Pid              *int32  `protobuf:"varint,2,req,name=pid" json:"pid,omitempty"`
	MemoryUsed       *uint64 `protobuf:"varint,3,req,name=memory_used,json=memoryUsed" json:"memory_used,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{5} }

func (m *Pong) GetToken() int64 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func (m *Pong) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *Pong) GetMemoryUsed() uint64 {
	if m != nil && m.MemoryUsed != nil {
		return *m.MemoryUsed
	}
	return 0
}

type DockerCommand struct {
	Cmd *DockerCmdType `protobuf:"varint,1,req,name=cmd,enum=sdc_internal.DockerCmdType" json:"cmd,omitempty"`
	// Making optional in case other later commands want to work with images
	ContainerId      *string `protobuf:"bytes,2,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DockerCommand) Reset()                    { *m = DockerCommand{} }
func (m *DockerCommand) String() string            { return proto.CompactTextString(m) }
func (*DockerCommand) ProtoMessage()               {}
func (*DockerCommand) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{6} }

func (m *DockerCommand) GetCmd() DockerCmdType {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return DockerCmdType_STOP
}

func (m *DockerCommand) GetContainerId() string {
	if m != nil && m.ContainerId != nil {
		return *m.ContainerId
	}
	return ""
}

type DockerCommandResult struct {
	Successful       *bool   `protobuf:"varint,1,req,name=successful" json:"successful,omitempty"`
	Errstr           *string `protobuf:"bytes,2,opt,name=errstr" json:"errstr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DockerCommandResult) Reset()                    { *m = DockerCommandResult{} }
func (m *DockerCommandResult) String() string            { return proto.CompactTextString(m) }
func (*DockerCommandResult) ProtoMessage()               {}
func (*DockerCommandResult) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{7} }

func (m *DockerCommandResult) GetSuccessful() bool {
	if m != nil && m.Successful != nil {
		return *m.Successful
	}
	return false
}

func (m *DockerCommandResult) GetErrstr() string {
	if m != nil && m.Errstr != nil {
		return *m.Errstr
	}
	return ""
}

type SwarmStateCommand struct {
	ContainerId      *string `protobuf:"bytes,2,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SwarmStateCommand) Reset()                    { *m = SwarmStateCommand{} }
func (m *SwarmStateCommand) String() string            { return proto.CompactTextString(m) }
func (*SwarmStateCommand) ProtoMessage()               {}
func (*SwarmStateCommand) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{8} }

func (m *SwarmStateCommand) GetContainerId() string {
	if m != nil && m.ContainerId != nil {
		return *m.ContainerId
	}
	return ""
}

type SwarmStateResult struct {
	Successful       *bool                   `protobuf:"varint,1,req,name=successful" json:"successful,omitempty"`
	Errstr           *string                 `protobuf:"bytes,2,opt,name=errstr" json:"errstr,omitempty"`
	State            *draiosproto.SwarmState `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SwarmStateResult) Reset()                    { *m = SwarmStateResult{} }
func (m *SwarmStateResult) String() string            { return proto.CompactTextString(m) }
func (*SwarmStateResult) ProtoMessage()               {}
func (*SwarmStateResult) Descriptor() ([]byte, []int) { return fileDescriptorSdcInternal, []int{9} }

func (m *SwarmStateResult) GetSuccessful() bool {
	if m != nil && m.Successful != nil {
		return *m.Successful
	}
	return false
}

func (m *SwarmStateResult) GetErrstr() string {
	if m != nil && m.Errstr != nil {
		return *m.Errstr
	}
	return ""
}

func (m *SwarmStateResult) GetState() *draiosproto.SwarmState {
	if m != nil {
		return m.State
	}
	return nil
}

type OrchestratorEventsStreamCommand struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	CaCert           *string `protobuf:"bytes,2,req,name=ca_cert,json=caCert" json:"ca_cert,omitempty"`
	ClientCert       *string `protobuf:"bytes,3,req,name=client_cert,json=clientCert" json:"client_cert,omitempty"`
	ClientKey        *string `protobuf:"bytes,4,req,name=client_key,json=clientKey" json:"client_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrchestratorEventsStreamCommand) Reset()         { *m = OrchestratorEventsStreamCommand{} }
func (m *OrchestratorEventsStreamCommand) String() string { return proto.CompactTextString(m) }
func (*OrchestratorEventsStreamCommand) ProtoMessage()    {}
func (*OrchestratorEventsStreamCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorSdcInternal, []int{10}
}

func (m *OrchestratorEventsStreamCommand) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *OrchestratorEventsStreamCommand) GetCaCert() string {
	if m != nil && m.CaCert != nil {
		return *m.CaCert
	}
	return ""
}

func (m *OrchestratorEventsStreamCommand) GetClientCert() string {
	if m != nil && m.ClientCert != nil {
		return *m.ClientCert
	}
	return ""
}

func (m *OrchestratorEventsStreamCommand) GetClientKey() string {
	if m != nil && m.ClientKey != nil {
		return *m.ClientKey
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainerMounts)(nil), "sdc_internal.container_mounts")
	proto.RegisterType((*MountedFsResponse)(nil), "sdc_internal.mounted_fs_response")
	proto.RegisterType((*ContainerInfo)(nil), "sdc_internal.container_info")
	proto.RegisterType((*MountedFsRequest)(nil), "sdc_internal.mounted_fs_request")
	proto.RegisterType((*Ping)(nil), "sdc_internal.ping")
	proto.RegisterType((*Pong)(nil), "sdc_internal.pong")
	proto.RegisterType((*DockerCommand)(nil), "sdc_internal.docker_command")
	proto.RegisterType((*DockerCommandResult)(nil), "sdc_internal.docker_command_result")
	proto.RegisterType((*SwarmStateCommand)(nil), "sdc_internal.swarm_state_command")
	proto.RegisterType((*SwarmStateResult)(nil), "sdc_internal.swarm_state_result")
	proto.RegisterType((*OrchestratorEventsStreamCommand)(nil), "sdc_internal.orchestrator_events_stream_command")
	proto.RegisterEnum("sdc_internal.CointerfaceMessageType", CointerfaceMessageType_name, CointerfaceMessageType_value)
	proto.RegisterEnum("sdc_internal.DockerCmdType", DockerCmdType_name, DockerCmdType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CoInterface service

type CoInterfaceClient interface {
	PerformDockerCommand(ctx context.Context, in *DockerCommand, opts ...grpc.CallOption) (*DockerCommandResult, error)
	PerformPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	PerformSwarmState(ctx context.Context, in *SwarmStateCommand, opts ...grpc.CallOption) (*SwarmStateResult, error)
	PerformOrchestratorEventsStream(ctx context.Context, in *OrchestratorEventsStreamCommand, opts ...grpc.CallOption) (CoInterface_PerformOrchestratorEventsStreamClient, error)
}

type coInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewCoInterfaceClient(cc *grpc.ClientConn) CoInterfaceClient {
	return &coInterfaceClient{cc}
}

func (c *coInterfaceClient) PerformDockerCommand(ctx context.Context, in *DockerCommand, opts ...grpc.CallOption) (*DockerCommandResult, error) {
	out := new(DockerCommandResult)
	err := grpc.Invoke(ctx, "/sdc_internal.CoInterface/PerformDockerCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coInterfaceClient) PerformPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := grpc.Invoke(ctx, "/sdc_internal.CoInterface/PerformPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coInterfaceClient) PerformSwarmState(ctx context.Context, in *SwarmStateCommand, opts ...grpc.CallOption) (*SwarmStateResult, error) {
	out := new(SwarmStateResult)
	err := grpc.Invoke(ctx, "/sdc_internal.CoInterface/PerformSwarmState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coInterfaceClient) PerformOrchestratorEventsStream(ctx context.Context, in *OrchestratorEventsStreamCommand, opts ...grpc.CallOption) (CoInterface_PerformOrchestratorEventsStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CoInterface_serviceDesc.Streams[0], c.cc, "/sdc_internal.CoInterface/PerformOrchestratorEventsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &coInterfacePerformOrchestratorEventsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CoInterface_PerformOrchestratorEventsStreamClient interface {
	Recv() (*draiosproto.CongroupUpdateEvent, error)
	grpc.ClientStream
}

type coInterfacePerformOrchestratorEventsStreamClient struct {
	grpc.ClientStream
}

func (x *coInterfacePerformOrchestratorEventsStreamClient) Recv() (*draiosproto.CongroupUpdateEvent, error) {
	m := new(draiosproto.CongroupUpdateEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CoInterface service

type CoInterfaceServer interface {
	PerformDockerCommand(context.Context, *DockerCommand) (*DockerCommandResult, error)
	PerformPing(context.Context, *Ping) (*Pong, error)
	PerformSwarmState(context.Context, *SwarmStateCommand) (*SwarmStateResult, error)
	PerformOrchestratorEventsStream(*OrchestratorEventsStreamCommand, CoInterface_PerformOrchestratorEventsStreamServer) error
}

func RegisterCoInterfaceServer(s *grpc.Server, srv CoInterfaceServer) {
	s.RegisterService(&_CoInterface_serviceDesc, srv)
}

func _CoInterface_PerformDockerCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoInterfaceServer).PerformDockerCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdc_internal.CoInterface/PerformDockerCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoInterfaceServer).PerformDockerCommand(ctx, req.(*DockerCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoInterface_PerformPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoInterfaceServer).PerformPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdc_internal.CoInterface/PerformPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoInterfaceServer).PerformPing(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoInterface_PerformSwarmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwarmStateCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoInterfaceServer).PerformSwarmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdc_internal.CoInterface/PerformSwarmState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoInterfaceServer).PerformSwarmState(ctx, req.(*SwarmStateCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoInterface_PerformOrchestratorEventsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrchestratorEventsStreamCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoInterfaceServer).PerformOrchestratorEventsStream(m, &coInterfacePerformOrchestratorEventsStreamServer{stream})
}

type CoInterface_PerformOrchestratorEventsStreamServer interface {
	Send(*draiosproto.CongroupUpdateEvent) error
	grpc.ServerStream
}

type coInterfacePerformOrchestratorEventsStreamServer struct {
	grpc.ServerStream
}

func (x *coInterfacePerformOrchestratorEventsStreamServer) Send(m *draiosproto.CongroupUpdateEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _CoInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sdc_internal.CoInterface",
	HandlerType: (*CoInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PerformDockerCommand",
			Handler:    _CoInterface_PerformDockerCommand_Handler,
		},
		{
			MethodName: "PerformPing",
			Handler:    _CoInterface_PerformPing_Handler,
		},
		{
			MethodName: "PerformSwarmState",
			Handler:    _CoInterface_PerformSwarmState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PerformOrchestratorEventsStream",
			Handler:       _CoInterface_PerformOrchestratorEventsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdc_internal.proto",
}

func (m *ContainerMounts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContainerMounts) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ContainerId == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.ContainerId)))
		i += copy(dAtA[i:], *m.ContainerId)
	}
	if len(m.Mounts) > 0 {
		for _, msg := range m.Mounts {
			dAtA[i] = 0x12
			i++
			i = encodeVarintSdcInternal(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *MountedFsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MountedFsResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Containers) > 0 {
		for _, msg := range m.Containers {
			dAtA[i] = 0xa
			i++
			i = encodeVarintSdcInternal(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ContainerInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContainerInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.Id)))
		i += copy(dAtA[i:], *m.Id)
	}
	if m.Pid == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(*m.Pid))
	}
	if m.Vpid == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x18
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(*m.Vpid))
	}
	if m.Root == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x22
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.Root)))
		i += copy(dAtA[i:], *m.Root)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *MountedFsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MountedFsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Containers) > 0 {
		for _, msg := range m.Containers {
			dAtA[i] = 0xa
			i++
			i = encodeVarintSdcInternal(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Ping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ping) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Token == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(*m.Token))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Pong) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pong) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Token == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(*m.Token))
	}
	if m.Pid == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(*m.Pid))
	}
	if m.MemoryUsed == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x18
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(*m.MemoryUsed))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DockerCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DockerCommand) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Cmd == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(*m.Cmd))
	}
	if m.ContainerId != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.ContainerId)))
		i += copy(dAtA[i:], *m.ContainerId)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DockerCommandResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DockerCommandResult) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Successful == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		if *m.Successful {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Errstr != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.Errstr)))
		i += copy(dAtA[i:], *m.Errstr)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SwarmStateCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwarmStateCommand) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ContainerId != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.ContainerId)))
		i += copy(dAtA[i:], *m.ContainerId)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SwarmStateResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwarmStateResult) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Successful == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		if *m.Successful {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Errstr != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.Errstr)))
		i += copy(dAtA[i:], *m.Errstr)
	}
	if m.State != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(m.State.Size()))
		n1, err := m.State.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *OrchestratorEventsStreamCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrchestratorEventsStreamCommand) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Url == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.Url)))
		i += copy(dAtA[i:], *m.Url)
	}
	if m.CaCert == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.CaCert)))
		i += copy(dAtA[i:], *m.CaCert)
	}
	if m.ClientCert == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.ClientCert)))
		i += copy(dAtA[i:], *m.ClientCert)
	}
	if m.ClientKey == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x22
		i++
		i = encodeVarintSdcInternal(dAtA, i, uint64(len(*m.ClientKey)))
		i += copy(dAtA[i:], *m.ClientKey)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintSdcInternal(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ContainerMounts) Size() (n int) {
	var l int
	_ = l
	if m.ContainerId != nil {
		l = len(*m.ContainerId)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if len(m.Mounts) > 0 {
		for _, e := range m.Mounts {
			l = e.Size()
			n += 1 + l + sovSdcInternal(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MountedFsResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.Containers) > 0 {
		for _, e := range m.Containers {
			l = e.Size()
			n += 1 + l + sovSdcInternal(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ContainerInfo) Size() (n int) {
	var l int
	_ = l
	if m.Id != nil {
		l = len(*m.Id)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.Pid != nil {
		n += 1 + sovSdcInternal(uint64(*m.Pid))
	}
	if m.Vpid != nil {
		n += 1 + sovSdcInternal(uint64(*m.Vpid))
	}
	if m.Root != nil {
		l = len(*m.Root)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MountedFsRequest) Size() (n int) {
	var l int
	_ = l
	if len(m.Containers) > 0 {
		for _, e := range m.Containers {
			l = e.Size()
			n += 1 + l + sovSdcInternal(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Ping) Size() (n int) {
	var l int
	_ = l
	if m.Token != nil {
		n += 1 + sovSdcInternal(uint64(*m.Token))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Pong) Size() (n int) {
	var l int
	_ = l
	if m.Token != nil {
		n += 1 + sovSdcInternal(uint64(*m.Token))
	}
	if m.Pid != nil {
		n += 1 + sovSdcInternal(uint64(*m.Pid))
	}
	if m.MemoryUsed != nil {
		n += 1 + sovSdcInternal(uint64(*m.MemoryUsed))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DockerCommand) Size() (n int) {
	var l int
	_ = l
	if m.Cmd != nil {
		n += 1 + sovSdcInternal(uint64(*m.Cmd))
	}
	if m.ContainerId != nil {
		l = len(*m.ContainerId)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DockerCommandResult) Size() (n int) {
	var l int
	_ = l
	if m.Successful != nil {
		n += 2
	}
	if m.Errstr != nil {
		l = len(*m.Errstr)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SwarmStateCommand) Size() (n int) {
	var l int
	_ = l
	if m.ContainerId != nil {
		l = len(*m.ContainerId)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SwarmStateResult) Size() (n int) {
	var l int
	_ = l
	if m.Successful != nil {
		n += 2
	}
	if m.Errstr != nil {
		l = len(*m.Errstr)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.State != nil {
		l = m.State.Size()
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OrchestratorEventsStreamCommand) Size() (n int) {
	var l int
	_ = l
	if m.Url != nil {
		l = len(*m.Url)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.CaCert != nil {
		l = len(*m.CaCert)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.ClientCert != nil {
		l = len(*m.ClientCert)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.ClientKey != nil {
		l = len(*m.ClientKey)
		n += 1 + l + sovSdcInternal(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSdcInternal(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSdcInternal(x uint64) (n int) {
	return sovSdcInternal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ContainerMounts) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: container_mounts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: container_mounts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ContainerId = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mounts = append(m.Mounts, &draiosproto.MountedFs{})
			if err := m.Mounts[len(m.Mounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MountedFsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: mounted_fs_response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: mounted_fs_response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Containers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Containers = append(m.Containers, &ContainerMounts{})
			if err := m.Containers[len(m.Containers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContainerInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: container_info: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: container_info: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Id = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pid = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vpid", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Vpid = &v
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Root = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MountedFsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: mounted_fs_request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: mounted_fs_request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Containers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Containers = append(m.Containers, &ContainerInfo{})
			if err := m.Containers[len(m.Containers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ping) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Token = &v
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Pong) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: pong: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: pong: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Token = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pid = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryUsed", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MemoryUsed = &v
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DockerCommand) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: docker_command: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: docker_command: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			var v DockerCmdType
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (DockerCmdType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Cmd = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ContainerId = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DockerCommandResult) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: docker_command_result: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: docker_command_result: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Successful", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Successful = &b
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Errstr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Errstr = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwarmStateCommand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: swarm_state_command: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: swarm_state_command: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ContainerId = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwarmStateResult) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: swarm_state_result: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: swarm_state_result: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Successful", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Successful = &b
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Errstr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Errstr = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.State == nil {
				m.State = &draiosproto.SwarmState{}
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrchestratorEventsStreamCommand) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: orchestrator_events_stream_command: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: orchestrator_events_stream_command: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Url = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaCert", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.CaCert = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientCert", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClientCert = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdcInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClientKey = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipSdcInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSdcInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSdcInternal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSdcInternal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSdcInternal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSdcInternal
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSdcInternal
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSdcInternal(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSdcInternal = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSdcInternal   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("sdc_internal.proto", fileDescriptorSdcInternal) }

var fileDescriptorSdcInternal = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xed, 0xa4, 0x3f, 0x27, 0x55, 0x30, 0xa7, 0xbb, 0xdb, 0x10, 0x75, 0xb3, 0xa9, 0x11,
	0xa8, 0xda, 0x8b, 0xb0, 0x2a, 0x17, 0x70, 0x81, 0x90, 0x42, 0x6a, 0xed, 0x56, 0x4b, 0xe3, 0x68,
	0x9c, 0x80, 0xb4, 0x5c, 0x8c, 0x2c, 0x7b, 0x52, 0xa2, 0xc6, 0x1e, 0x33, 0x33, 0x5e, 0x54, 0xc1,
	0x3b, 0x70, 0xcb, 0x23, 0x71, 0xc9, 0x0b, 0x20, 0xa1, 0xf2, 0x1a, 0x5c, 0x20, 0x8f, 0x5d, 0xaf,
	0x1d, 0xda, 0x05, 0x69, 0xef, 0xce, 0x7c, 0xe7, 0x9c, 0x6f, 0xbe, 0xe3, 0xf3, 0x8d, 0x01, 0x65,
	0x14, 0xd2, 0x55, 0xa2, 0x98, 0x48, 0x82, 0xf5, 0x28, 0x15, 0x5c, 0x71, 0xdc, 0xaf, 0x63, 0xfd,
	0xfd, 0x48, 0x04, 0x2b, 0x2e, 0x8b, 0x9c, 0xb3, 0x04, 0x3b, 0xe4, 0x89, 0x0a, 0x56, 0x09, 0x13,
	0x34, 0xe6, 0x59, 0xa2, 0x24, 0x1e, 0xc3, 0xfe, 0x1b, 0x6c, 0x15, 0xf5, 0x8c, 0xa1, 0x79, 0xb2,
	0x47, 0x3a, 0x15, 0x76, 0x1e, 0xe1, 0x27, 0xb0, 0x5d, 0x14, 0xf7, 0xcc, 0xa1, 0x75, 0xd2, 0x39,
	0x3d, 0x1c, 0x15, 0xac, 0x9a, 0x74, 0xa4, 0x53, 0x2c, 0xa2, 0x4b, 0x49, 0xca, 0x32, 0x67, 0x01,
	0x07, 0x6f, 0x50, 0x2a, 0x98, 0x4c, 0x79, 0x22, 0x19, 0x7e, 0x09, 0x50, 0xd1, 0xca, 0x9e, 0xa1,
	0xb9, 0x06, 0xa3, 0xc6, 0x0c, 0x9b, 0xf2, 0x48, 0xad, 0xc3, 0x79, 0x05, 0xdd, 0x9a, 0xd4, 0x64,
	0xc9, 0xb1, 0x0b, 0x66, 0x25, 0xd9, 0x5c, 0x45, 0x68, 0x83, 0x95, 0xae, 0xa2, 0x9e, 0x39, 0x34,
	0x4f, 0x5a, 0x24, 0x0f, 0x11, 0xa1, 0xf5, 0x3a, 0x87, 0x2c, 0x0d, 0xe9, 0x38, 0xc7, 0x04, 0xe7,
	0xaa, 0xd7, 0xd2, 0x7d, 0x3a, 0x76, 0x08, 0x60, 0x43, 0xf2, 0x0f, 0x19, 0x93, 0x0a, 0xbf, 0xb8,
	0x43, 0xf1, 0xd1, 0x7d, 0x8a, 0x73, 0x45, 0x0d, 0xbd, 0x47, 0xd0, 0x4a, 0x57, 0xc9, 0x25, 0x3e,
	0x80, 0xb6, 0xe2, 0x57, 0x2c, 0xd1, 0x42, 0x2d, 0x52, 0x1c, 0x1c, 0x0f, 0x5a, 0x29, 0xbf, 0x2f,
	0x5b, 0x9f, 0xa4, 0x5d, 0x4c, 0xf2, 0x04, 0x3a, 0x31, 0x8b, 0xb9, 0xb8, 0xa6, 0x99, 0x64, 0xb7,
	0x03, 0x41, 0x01, 0x2d, 0x24, 0x8b, 0x9c, 0x08, 0xba, 0x11, 0x0f, 0xaf, 0x98, 0xa0, 0x21, 0x8f,
	0xe3, 0x20, 0xc9, 0x17, 0x67, 0x85, 0x71, 0xf1, 0x7d, 0xba, 0xa7, 0x8f, 0x9b, 0xba, 0x6f, 0x4b,
	0xe3, 0x88, 0xaa, 0xeb, 0x94, 0x91, 0xbc, 0xf2, 0x5f, 0x66, 0x30, 0x87, 0xc6, 0x86, 0x19, 0x1c,
	0x0f, 0x1e, 0x36, 0x6f, 0xc9, 0xf7, 0x9b, 0xad, 0x15, 0x0e, 0x00, 0x64, 0x16, 0x86, 0x4c, 0xca,
	0x65, 0xb6, 0xd6, 0x77, 0xee, 0x92, 0x1a, 0x82, 0x8f, 0x60, 0x9b, 0x09, 0x21, 0x95, 0x28, 0x59,
	0xcb, 0x93, 0xf3, 0x39, 0x1c, 0xc8, 0x1f, 0x03, 0x11, 0x53, 0xa9, 0x02, 0xc5, 0x2a, 0xed, 0xff,
	0x43, 0xca, 0xcf, 0x80, 0xf5, 0xce, 0x77, 0xd3, 0x81, 0x23, 0x68, 0x6b, 0x9e, 0x9e, 0x35, 0x34,
	0x4e, 0x3a, 0xa7, 0xbd, 0x86, 0xc9, 0x6b, 0xf7, 0x90, 0xa2, 0xcc, 0xf9, 0xc5, 0x00, 0x87, 0x8b,
	0xf0, 0x7b, 0x26, 0x95, 0x08, 0x14, 0x17, 0x94, 0xbd, 0x66, 0x89, 0x92, 0x54, 0x2a, 0xc1, 0x82,
	0xb8, 0x9a, 0xc3, 0x06, 0x2b, 0x13, 0xeb, 0xd2, 0xa3, 0x79, 0x88, 0x87, 0xb0, 0x13, 0x06, 0x34,
	0x64, 0x42, 0xe9, 0xf5, 0xee, 0x91, 0xed, 0x30, 0x98, 0x30, 0xa1, 0xf2, 0x0d, 0x87, 0xeb, 0x15,
	0x4b, 0x54, 0x91, 0xb4, 0x74, 0x12, 0x0a, 0x48, 0x17, 0x3c, 0x86, 0xf2, 0x44, 0xaf, 0xd8, 0x75,
	0x69, 0xdf, 0xbd, 0x02, 0x79, 0xc9, 0xae, 0x9f, 0xfe, 0x61, 0x40, 0x2f, 0xe4, 0x7a, 0xc3, 0xcb,
	0x20, 0x64, 0x34, 0x66, 0x52, 0x06, 0x97, 0x4c, 0xef, 0x17, 0x77, 0xa1, 0x35, 0x3b, 0x9f, 0x3e,
	0xb7, 0x0d, 0x1d, 0x79, 0xd3, 0xe7, 0xb6, 0x89, 0x08, 0xdd, 0x33, 0x6f, 0xf2, 0xd2, 0x25, 0x74,
	0xe2, 0x5d, 0x5c, 0x8c, 0xa7, 0x67, 0xb6, 0x85, 0x1f, 0xc0, 0xc3, 0x26, 0x46, 0x89, 0xeb, 0x2f,
	0xbe, 0x9e, 0xdb, 0x2d, 0x3c, 0x84, 0x03, 0xff, 0xdb, 0x31, 0xb9, 0xa0, 0xfe, 0x7c, 0x3c, 0x77,
	0xab, 0x9e, 0x36, 0x3e, 0x02, 0xac, 0x27, 0xca, 0x86, 0x6d, 0xfc, 0x18, 0x1c, 0x8f, 0x4c, 0x5e,
	0xb8, 0xfe, 0x9c, 0x8c, 0xe7, 0x1e, 0xa1, 0xee, 0x37, 0xee, 0x74, 0xee, 0x53, 0x7f, 0x4e, 0xdc,
	0xf1, 0x45, 0xd5, 0xbf, 0x83, 0x1f, 0xc1, 0xf1, 0x5b, 0xea, 0x4a, 0xba, 0xdd, 0xa7, 0x9f, 0xc2,
	0x7b, 0x1b, 0xae, 0xcd, 0x67, 0xf1, 0xe7, 0xde, 0xcc, 0x36, 0x70, 0x0f, 0xda, 0xb3, 0xf1, 0xc2,
	0x77, 0x6d, 0x13, 0x3b, 0xb0, 0xb3, 0x98, 0x16, 0x07, 0xeb, 0xf4, 0x6f, 0x13, 0x3a, 0x13, 0x7e,
	0x7e, 0xfb, 0x51, 0xf0, 0x3b, 0x78, 0x30, 0x63, 0x62, 0xc9, 0x45, 0x7c, 0xa6, 0xb9, 0x26, 0xe5,
	0x9e, 0x8e, 0xee, 0x7e, 0x1e, 0x45, 0xb6, 0xff, 0xe1, 0xdb, 0xb2, 0xa5, 0xf3, 0x9c, 0x2d, 0xfc,
	0x0c, 0x3a, 0x25, 0xf9, 0x2c, 0x7f, 0xf8, 0xd8, 0xec, 0xca, 0x7f, 0x06, 0xfd, 0x4d, 0x8c, 0x27,
	0x97, 0xce, 0x16, 0xbe, 0x82, 0xf7, 0xcb, 0x46, 0x3f, 0x77, 0x9a, 0x9f, 0x3b, 0x0c, 0x8f, 0x9b,
	0xa5, 0x77, 0xbc, 0x92, 0xfe, 0xf0, 0xfe, 0x92, 0x4a, 0xd4, 0x4f, 0xf0, 0xa4, 0xe4, 0xf6, 0x6a,
	0x76, 0x75, 0xb5, 0x5b, 0x7d, 0x6d, 0x56, 0x7c, 0xd6, 0xa4, 0xf9, 0x6f, 0x5b, 0xf7, 0x9d, 0xc6,
	0xf3, 0x08, 0x79, 0x72, 0x29, 0x78, 0x96, 0xd2, 0x2c, 0x8d, 0xf2, 0xbb, 0x75, 0x8f, 0xb3, 0xf5,
	0xcc, 0xf8, 0x0a, 0x7f, 0xbb, 0x19, 0x18, 0xbf, 0xdf, 0x0c, 0x8c, 0x3f, 0x6f, 0x06, 0xc6, 0xaf,
	0x7f, 0x0d, 0xb6, 0x5e, 0x18, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x2a, 0x29, 0x80, 0xb7,
	0x06, 0x00, 0x00,
}
