/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sysdigcloud_sdjagent_CLibrary */

#ifndef _Included_com_sysdigcloud_sdjagent_CLibrary
#define _Included_com_sysdigcloud_sdjagent_CLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sysdigcloud_sdjagent_CLibrary
 * Method:    seteuid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sysdigcloud_sdjagent_CLibrary_real_1seteuid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sysdigcloud_sdjagent_CLibrary
 * Method:    setegid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sysdigcloud_sdjagent_CLibrary_real_1setegid
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif