#!/bin/bash
set -exo pipefail

if [[ $(uname) == "Darwin" ]]; then
  SCRIPT=$(greadlink -f $0)
else
  SCRIPT=$(readlink -f $0)
fi
AGENT_SOURCEDIR=$(dirname $SCRIPT)
DIGWATCH_SOURCEDIR=$(dirname $SCRIPT)/../digwatch

if [ -z "$WORKDIR" ]; then
	WORKDIR=$AGENT_SOURCEDIR/..
fi

DEPENDENCIES=$WORKDIR/agent/dependencies

if [ ! -d "$DEPENDENCIES" ]; then
	mkdir -p $DEPENDENCIES
fi

CMAKE_DIR=$DEPENDENCIES/cmake-3.3.2
if [ ! -d "$CMAKE_DIR" ]; then
	cd $DEPENDENCIES
	wget https://s3.amazonaws.com/download.draios.com/dependencies/cmake-3.3.2.tar.gz
	tar -xzf cmake-3.3.2.tar.gz
	cd $CMAKE_DIR
	./bootstrap
	make
fi

if [ -z "$DIGWATCH_VERSION" ]; then
	DIGWATCH_VERSION="0.1.1dev"
fi

if [ -z "$BUILD_DRIVER" ]; then
  BUILD_DRIVER=ON
fi

DIGWATCH_BUILD_DIR=$WORKDIR/digweatch/build
mkdir -p $DIGWATCH_BUILD_DIR/debug
mkdir -p $DIGWATCH_BUILD_DIR/release

cd $DIGWATCH_BUILD_DIR/debug
$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DDIGWATCH_VERSION=$DIGWATCH_VERSION -DDIR_ETC=/etc -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DRIVER=${BUILD_DRIVER} $DIGWATCH_SOURCEDIR
cd $DIGWATCH_BUILD_DIR/release
$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Release -DDIGWATCH_VERSION=$DIGWATCH_VERSION -DDIR_ETC=/etc -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DRIVER=${BUILD_DRIVER} $DIGWATCH_SOURCEDIR
