#!/bin/bash
set -exo pipefail

if [[ $(uname) == "Darwin" ]]; then
  SCRIPT=$(greadlink -f $0)
else
  SCRIPT=$(readlink -f $0)
fi
AGENT_SOURCEDIR=$(dirname $SCRIPT)
SYSDIG_SOURCEDIR=$(dirname $SCRIPT)/../sysdig

if [ -z "$WORKDIR" ]; then
	WORKDIR=$AGENT_SOURCEDIR/..
fi

DEPENDENCIES=$WORKDIR/agent/dependencies

if [ ! -d "$DEPENDENCIES" ]; then
	mkdir -p $DEPENDENCIES
fi

CMAKE_DIR=$DEPENDENCIES/cmake-3.0.0
if [ ! -d "$CMAKE_DIR" ]; then
	cd $DEPENDENCIES
	wget https://s3.amazonaws.com/download.draios.com/dependencies/cmake-3.0.0.tar.gz
	tar -xzf cmake-3.0.0.tar.gz
	cd $CMAKE_DIR
	./bootstrap
	make
fi

if [ -z "$SYSDIG_VERSION" ]; then
	SYSDIG_VERSION="0.1.1-dev"
fi

SYSDIG_BUILD_DIR=$WORKDIR/sysdig/build
mkdir -p $SYSDIG_BUILD_DIR/debug
mkdir -p $SYSDIG_BUILD_DIR/release

cd $SYSDIG_BUILD_DIR/debug
$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DSYSDIG_VERSION=$SYSDIG_VERSION -DDIR_ETC=/etc -DCMAKE_INSTALL_PREFIX=/usr $SYSDIG_SOURCEDIR
cd $SYSDIG_BUILD_DIR/release
$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Release -DSYSDIG_VERSION=$SYSDIG_VERSION -DDIR_ETC=/etc -DCMAKE_INSTALL_PREFIX=/usr $SYSDIG_SOURCEDIR
