#!/bin/bash
set -exo pipefail

if [[ $(uname) == "Darwin" ]]; then
  SCRIPT=$(greadlink -f $0)
else
  SCRIPT=$(readlink -f $0)
fi
AGENT_SOURCEDIR=$(dirname $SCRIPT)
FALCO_SOURCEDIR=$(dirname $SCRIPT)/../falco

if [ -z "$WORKDIR" ]; then
	WORKDIR=$AGENT_SOURCEDIR/..
fi

DEPENDENCIES=$WORKDIR/agent/dependencies

if [ ! -d "$DEPENDENCIES" ]; then
	mkdir -p $DEPENDENCIES
fi

CMAKE_DIR=$DEPENDENCIES/cmake-3.3.2
if [ ! -d "$CMAKE_DIR" ]; then
	cd $DEPENDENCIES
	wget https://s3.amazonaws.com/download.draios.com/dependencies/cmake-3.3.2.tar.gz
	tar -xzf cmake-3.3.2.tar.gz
	cd $CMAKE_DIR
	./bootstrap
	make
fi

if [ -z "$FALCO_VERSION" ]; then
	FALCO_VERSION="0.1.1dev"
fi

if [ -z "$BUILD_DRIVER" ]; then
  BUILD_DRIVER=ON
fi

FALCO_BUILD_DIR=$WORKDIR/falco/build
mkdir -p $FALCO_BUILD_DIR/debug
mkdir -p $FALCO_BUILD_DIR/release

cd $FALCO_BUILD_DIR/debug
$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DFALCO_VERSION=$FALCO_VERSION -DDIR_ETC=/etc -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_DRIVER} $FALCO_SOURCEDIR
cd $FALCO_BUILD_DIR/release
$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Release -DFALCO_VERSION=$FALCO_VERSION -DDIR_ETC=/etc -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_DRIVER} $FALCO_SOURCEDIR
