#!/bin/bash
set -exo pipefail

if [[ $(uname) == "Darwin" ]]; then
  SCRIPT=$(greadlink -f $0)
else
  SCRIPT=$(readlink -f $0)
fi

AGENT_SOURCEDIR=$(dirname $SCRIPT)

if [ -z "$WORKDIR" ]; then
	WORKDIR=$AGENT_SOURCEDIR/..
fi

DEPENDENCIES=$WORKDIR/agent/dependencies
DEPENDENCIES_URL="https://s3.amazonaws.com/download.draios.com/dependencies"

if [ ! -d "$DEPENDENCIES" ]; then
	mkdir -p $DEPENDENCIES
fi

ZLIB_DIR=$DEPENDENCIES/zlib-1.2.8
if [ ! -d "$ZLIB_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/zlib-1.2.8.tar.gz
	tar -xzf zlib-1.2.8.tar.gz
	cd $ZLIB_DIR
	./configure
	make
fi

JQ_DIR=$DEPENDENCIES/jq-1.5
if [ ! -d "$JQ_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/jq-1.5.tar.gz
	tar -xzf jq-1.5.tar.gz
	cd $JQ_DIR
	./configure --disable-maintainer-mode --enable-all-static --disable-dependency-tracking
	make LDFLAGS=-all-static
fi

PROTBUF_DIR=$DEPENDENCIES/protobuf-2.5.0
if [ ! -d "$PROTBUF_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/protobuf-2.5.0.tar.bz2
	tar -xjf protobuf-2.5.0.tar.bz2
	cd $PROTBUF_DIR
	CPPFLAGS=-I$ZLIB_DIR LDFLAGS=-L$ZLIB_DIR ./configure --with-zlib
	make
fi

OPENSSL_VER=1.0.2d
OPENSSL_EXT=tar.gz
OPENSSL_DIR=$DEPENDENCIES/openssl-$OPENSSL_VER
if [ ! -d "$OPENSSL_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/openssl-$OPENSSL_VER.$OPENSSL_EXT
	tar -xzf openssl-$OPENSSL_VER.$OPENSSL_EXT
	cd $OPENSSL_DIR
	./config shared --prefix=$OPENSSL_DIR/target
	make install
	cd ..
fi

POCO_DIR=$DEPENDENCIES/poco-1.4.6p4-all
if [ ! -d "$POCO_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/poco-1.4.6p4-all.tar.gz
	tar -xzf poco-1.4.6p4-all.tar.gz
	cd $POCO_DIR
	patch -p1 < $AGENT_SOURCEDIR/patches/poco_libc_canonname_bug.patch
	./configure --prefix=./target --static --no-samples --no-tests --omit=Data/MySQL,Data/ODBC,PageCompiler --include-path=$OPENSSL_DIR/target/include
	make install
	cd ..
fi

GTEST_DIR=$DEPENDENCIES/gtest-1.7.0
if [ ! -d "$GTEST_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/gtest-1.7.0.zip
	unzip gtest-1.7.0.zip
	cd $GTEST_DIR
	g++ -Iinclude -c fused-src/gtest/gtest-all.cc -o gtest-all.o
	g++ -Iinclude -c fused-src/gtest/gtest_main.cc -o gtest_main.o
  	ar -rv libgtest.a gtest-all.o
  	ar -rv libgtest_main.a gtest_main.o
fi

if [ ! -d "$DEPENDENCIES/simpleopt" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/simpleopt-3.6.zip
	unzip simpleopt-3.6.zip
fi

CMAKE_DIR=$DEPENDENCIES/cmake-3.3.2
if [ ! -d "$CMAKE_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/cmake-3.3.2.tar.gz
	tar -xzf cmake-3.3.2.tar.gz
	cd $CMAKE_DIR
	./bootstrap
	make
fi

LIBSSH_DIR=$DEPENDENCIES/libssh-0.7.2
if [ ! -d "$LIBSSH_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/libssh-0.7.2.tar.xz
	tar -xf libssh-0.7.2.tar.xz
	cd $LIBSSH_DIR
	mkdir build
	cd build
	OPENSSL_ROOT_DIR=$OPENSSL_DIR/target $CMAKE_DIR/bin/cmake -DCMAKE_INSTALL_PREFIX=$LIBSSH_DIR/target -DZLIB_LIBRARY=$ZLIB_DIR -DZLIB_INCLUDE_DIR=$ZLIB_DIR -DWITH_STATIC_LIB=ON -DWITH_GSSAPI=OFF ..
	make -C src install
	make -C include install
fi

LUAJIT_DIR=$DEPENDENCIES/LuaJIT-2.0.3
if [ ! -d "$LUAJIT_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/LuaJIT-2.0.3.tar.gz
	tar -xzf LuaJIT-2.0.3.tar.gz
	cd $LUAJIT_DIR
	make
fi

CURL_NAME=curl-7.45.0
CURL_EXT=tar.bz2
CURL_DIR=$DEPENDENCIES/$CURL_NAME
if [ ! -d "$CURL_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/$CURL_NAME.$CURL_EXT
	tar -xjf $CURL_NAME.$CURL_EXT
	cd $CURL_DIR
	./configure --disable-shared  \
		--enable-optimize     \
		--disable-curldebug   \
		--disable-rt          \
		--enable-http         \
		--disable-ftp         \
		--disable-file        \
		--disable-ldap        \
		--disable-ldaps       \
		--disable-rtsp        \
		--disable-telnet      \
		--disable-tftp        \
		--disable-pop3        \
		--disable-imap        \
		--disable-smb         \
		--disable-smtp        \
		--disable-gopher      \
		--disable-sspi        \
		--disable-ntlm-wb     \
		--disable-tls-srp     \
		--without-winssl      \
		--without-darwinssl   \
		--with-ssl=$OPENSSL_DIR/target \
		--without-polarssl    \
		--without-cyassl      \
		--without-nss         \
		--without-axtls       \
		--without-ca-path     \
		--without-ca-bundle   \
		--without-libmetalink \
		--without-librtmp     \
		--without-winidn      \
		--without-libidn      \
		--without-nghttp2
	make
fi

B64_NAME=libb64-1.2
B64_EXT=src.zip
B64_DIR=$DEPENDENCIES/$B64_NAME
if [ ! -d "$B64_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/$B64_NAME.$B64_EXT
	unzip $B64_NAME.$B64_EXT
	cd $B64_DIR
	make
fi

JAVA_DIR=$DEPENDENCIES/jdk1.7.0_75
ARCH=$(uname -m)
if [ ! -d "$JAVA_DIR" ]; then
	cd $DEPENDENCIES
	if [[ $ARCH == "x86_64" ]]; then
		TARFILE=jdk-7u75-linux-x64.tar.bz2
	else
		TARFILE=jdk-7u75-linux-i586.tar.bz2
	fi
	wget $DEPENDENCIES_URL/$TARFILE
	tar -xjf $TARFILE
fi

MAVEN_DIR=$DEPENDENCIES/apache-maven-3.2.5
if [ ! -d "$MAVEN_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/apache-maven-3.2.5-bin.tar.gz
	tar -xzf apache-maven-3.2.5-bin.tar.gz
fi

BOOST_DIR=$DEPENDENCIES/boost_1_57_0
if [ ! -d "$BOOST_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/boost_1_57_0.tar.bz2
	tar xfj boost_1_57_0.tar.bz2
fi

YAMLCPP_DIR=$DEPENDENCIES/yaml-cpp-0.5.1
if [ ! -d "$YAMLCPP_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/yaml-cpp-0.5.1.tar.gz
	tar xfz yaml-cpp-0.5.1.tar.gz
	cd $YAMLCPP_DIR
	mkdir build
	cd build
	BOOST_ROOT=$BOOST_DIR $CMAKE_DIR/bin/cmake -DCMAKE_INSTALL_PREFIX=$YAMLCPP_DIR/target -DYAML_CPP_BUILD_CONTRIB=OFF ..
	make install
fi

SCONS_DIR=$DEPENDENCIES/scons-2.3.4
if [ ! -d "${SCONS_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/scons-2.3.4.tar.gz
	tar xfz scons-2.3.4.tar.gz
fi

PYTHON_VER=2.7.10
PYTHON_EXT=tgz
PYTHON_DIR=$DEPENDENCIES/Python-$PYTHON_VER
if [ ! -d "${PYTHON_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/Python-$PYTHON_VER.$PYTHON_EXT
	tar xfz Python-$PYTHON_VER.$PYTHON_EXT
	cd $PYTHON_DIR
	echo "zlib zlibmodule.c -I${ZLIB_DIR}/ -L${ZLIB_DIR}/ -lz" >> Modules/Setup.dist 
	./configure CPPFLAGS="-DUSE_SSL -I${OPENSSL_DIR}/target/include" LDFLAGS="-L${OPENSSL_DIR}/target/lib -Wl,-rpath=${OPENSSL_DIR}/target/lib" --prefix=$PYTHON_DIR/target --with-ensurepip=install --enable-unicode=ucs4
	make
	make install
fi

PYTHON26_VER=2.6.9
PYTHON26_EXT=tgz
PYTHON26_DIR=$DEPENDENCIES/Python-$PYTHON26_VER
if [ ! -d "${PYTHON26_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/Python-$PYTHON26_VER.$PYTHON26_EXT
	tar xfz Python-$PYTHON26_VER.$PYTHON26_EXT
	cd $PYTHON26_DIR
	echo "zlib zlibmodule.c -I${ZLIB_DIR}/ -L${ZLIB_DIR}/ -lz" >> Modules/Setup.dist 
	./configure CPPFLAGS="-DUSE_SSL -I${OPENSSL_DIR}/target/include" LDFLAGS="-L${OPENSSL_DIR}/target/lib -Wl,-rpath=${OPENSSL_DIR}/target/lib" --prefix=$PYTHON26_DIR/target --enable-unicode=ucs4
	make
	make install
	wget $DEPENDENCIES_URL/get-pip.py
	./target/bin/python get-pip.py
fi

if [ -z $STATSITE_VERSION ]; then
  STATSITE_VERSION=0.7.0-sysdig5
fi
STATSITE_DIR=$DEPENDENCIES/statsite-private-$STATSITE_VERSION
if [ ! -d "${STATSITE_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/statsite-private-$STATSITE_VERSION.zip
	unzip statsite-private-$STATSITE_VERSION.zip
	cd $STATSITE_DIR
	$PYTHON_DIR/target/bin/python $SCONS_DIR/script/scons
fi

POSTGRES_DIR=$DEPENDENCIES/postgresql-9.4.5
if [ ! -d "${POSTGRES_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/postgresql-9.4.5.tar.bz2
	tar xfj postgresql-9.4.5.tar.bz2
	cd $POSTGRES_DIR
	./configure --prefix=$POSTGRES_DIR/target --without-readline --without-zlib
	make
	make -C src/bin install
	make -C src/include install
	make -C src/interfaces install
fi

if [ -z "$AGENT_VERSION" ]; then
	AGENT_VERSION="0.1.1dev"
fi

if [ -z "$BUILD_DRIVER" ]; then
	BUILD_DRIVER=ON
fi

if [ -z "$ONLY_DEPS" ]; then
  AGENT_BUILD_DIR=$WORKDIR/agent/build
  mkdir -p $AGENT_BUILD_DIR/debug
  mkdir -p $AGENT_BUILD_DIR/release

  cd $AGENT_BUILD_DIR/debug
  $CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} $AGENT_SOURCEDIR
  cd $AGENT_BUILD_DIR/release
  $CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Release -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} $AGENT_SOURCEDIR
fi
