if(CPACK_GENERATOR MATCHES "DEB")
#	set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-@CPACK_DEBIAN_PACKAGE_ARCHITECTURE@")
	list(APPEND CPACK_INSTALL_COMMANDS "mkdir -p _CPack_Packages/${CPACK_TOPLEVEL_TAG}/${CPACK_GENERATOR}/${CPACK_PACKAGE_FILE_NAME}/agent/etc/init.d/")
	list(APPEND CPACK_INSTALL_COMMANDS "cp scripts/debian/dragent _CPack_Packages/${CPACK_TOPLEVEL_TAG}/${CPACK_GENERATOR}/${CPACK_PACKAGE_FILE_NAME}/agent/etc/init.d")
endif()

if(CPACK_GENERATOR MATCHES "RPM")
	list(APPEND CPACK_INSTALL_COMMANDS "mkdir -p _CPack_Packages/${CPACK_TOPLEVEL_TAG}/${CPACK_GENERATOR}/${CPACK_PACKAGE_FILE_NAME}/agent/etc/rc.d/init.d/")
	list(APPEND CPACK_INSTALL_COMMANDS "cp scripts/rpm/dragent _CPack_Packages/${CPACK_TOPLEVEL_TAG}/${CPACK_GENERATOR}/${CPACK_PACKAGE_FILE_NAME}/agent/etc/rc.d/init.d")

	list(APPEND CPACK_INSTALL_COMMANDS "mkdir -p _CPack_Packages/${CPACK_TOPLEVEL_TAG}/${CPACK_GENERATOR}/${CPACK_PACKAGE_FILE_NAME}/agent/${CPACK_DRAIOS_INSTALL_PREFIX}/bin")
	list(APPEND CPACK_INSTALL_COMMANDS "cp scripts/rpm/dragent.in _CPack_Packages/${CPACK_TOPLEVEL_TAG}/${CPACK_GENERATOR}/${CPACK_PACKAGE_FILE_NAME}/agent/${CPACK_DRAIOS_INSTALL_PREFIX}/bin")
endif()

if(CPACK_GENERATOR MATCHES "TGZ")
	set(CPACK_SET_DESTDIR "ON")
	set(CPACK_STRIP_FILES "OFF")
endif()
