#!/bin/bash
set -exo pipefail

if [ -z "$OS" ]; then
	OS="NA"
fi

if [[ $(uname) == "Darwin" ]]; then
  SCRIPT=$(greadlink -f $0)
else
  SCRIPT=$(readlink -f $0)
fi

if [ -z $MAKE_JOBS ]; then
    MAKE_JOBS=1
fi

echo "Building with parallelism $MAKE_JOBS"

# this script is called in two different contexts:
# - during the agent-builder image build it's copied
#   directly to /code/agent/build
# - during an actual agent build it's symlinked from
#   the agent repo (i.e. it's a symlink that points to
#   docker/builder/bootstrap-agent)
# this means that the readlink -f call above will return
# two different values based on the context this script
# is called, but we need to get a matching value of
# AGENT_SOURCEDIR in both cases. So detect when $SCRIPT
# points to inside the docker/builder directory
# and if so, go back up two directories to end up
# in /code/agent again
AGENT_SOURCEDIR=$(dirname $SCRIPT)
if [[ "$AGENT_SOURCEDIR" = */docker/builder ]]
then
	AGENT_SOURCEDIR=$AGENT_SOURCEDIR/../..
fi
ROOT_SOURCEDIR=$AGENT_SOURCEDIR/..
ARCH=$(uname -m)

if [ -z "$WORKDIR" ]; then
	WORKDIR=$AGENT_SOURCEDIR/..
fi

DEPENDENCIES=$WORKDIR/agent/dependencies
DEPENDENCIES_URL="https://s3.amazonaws.com/download.draios.com/dependencies"

if [ ! -d "$DEPENDENCIES" ]; then
	mkdir -p $DEPENDENCIES
fi

if [ $OS == "Windows_NT" ]; then
	export PATH=/bin:/cygdrive/c/cygwin64/bin:$PATH
	export LD_LIBRARY_PATH=/bin:/cygdrive/c/cygwin64/bin
fi

VALGRIND_DIR=$DEPENDENCIES/valgrind-3.15.0
if [ ! -d "$VALGRIND_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/valgrind-3.15.0.tar.bz2
	tar -xjf valgrind-3.15.0.tar.bz2
	cd $VALGRIND_DIR
	./configure
	make -j $MAKE_JOBS
	make -j $MAKE_JOBS install
fi

if [ $OS != "Windows_NT" ]; then
	ZLIB_VER=1.2.11
else
	ZLIB_VER=1.2.8
fi

ZLIB_DIR=$DEPENDENCIES/zlib-$ZLIB_VER

if [ ! -d "$ZLIB_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/zlib-$ZLIB_VER.tar.gz
	tar -xzf zlib-$ZLIB_VER.tar.gz
	cd $ZLIB_DIR
	./configure
	make -j $MAKE_JOBS
fi

JQ_DIR=$DEPENDENCIES/jq-1.5
if [ ! -d "$JQ_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/jq-1.5.tar.gz
	tar -xzf jq-1.5.tar.gz
	wget -O jq-1.5-fix-tokenadd.patch https://github.com/stedolan/jq/commit/8eb1367ca44e772963e704a700ef72ae2e12babd.patch
	cd $JQ_DIR
	patch < ../jq-1.5-fix-tokenadd.patch
	./configure --disable-maintainer-mode --enable-all-static --disable-dependency-tracking
	make LDFLAGS=-all-static -j $MAKE_JOBS
fi

if [ $OS != "Windows_NT" ]; then
	TBB_DIR=$DEPENDENCIES/tbb-2018_U5
	if [ ! -d "$TBB_DIR" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/tbb-2018_U5.tar.gz
		tar -xzf tbb-2018_U5.tar.gz
		cd $TBB_DIR
		make tbb_build_dir=${TBB_DIR}/build tbb_build_prefix=lib extra_inc=big_iron.inc -j $MAKE_JOBS
	fi
fi

# The njson vs json is intentional. The tarball has njson-x.y.z in the
# name, but it unpacks to json-x.y.z.
NJSON_DIR=$DEPENDENCIES/json-3.3.0
if [ ! -d "$NJSON_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/njson-3.3.0.tar.gz
	tar -xzf njson-3.3.0.tar.gz
	# No build neeeded, all of the code is in a single header file.
fi

if [[ "$ARCH" == "s390x" ]]; then
GO_DIR=/usr/local/go
if [ ! -d "$GO_DIR" ]; then
	mkdir -p $GO_DIR
	wget https://storage.googleapis.com/golang/go1.8.1.linux-s390x.tar.gz
	tar -C $GO_DIR/.. -xzf go1.8.1.linux-s390x.tar.gz
	ln -s $GO_DIR/bin/go /usr/local/bin
	ln -s /usr/bin/gcc s390x-linux-gnu-gcc
	rm go1.8.1.linux-s390x.tar.gz
fi
# SLES doesn't have dpkg but we need it for CPackDeb
# Build it ourselves
DPKG_VER=1.18.23
DPKG_DIR=$DEPENDENCIES/dpkg-$DPKG_VER
if [ ! -d "$DPKG_DIR" ]; then
	cd $DEPENDENCIES
	git clone https://anonscm.debian.org/git/dpkg/dpkg.git $DPKG_DIR
	cd $DPKG_DIR
	git checkout tags/$DPKG_VER
	autoreconf -f -i
	./configure
	make -j $MAKE_JOBS
	make -j $MAKE_JOBS install
fi
fi

PROTOBUF_V3_DIR=$DEPENDENCIES/protobuf-3.9.2
if [ ! -d "$PROTOBUF_V3_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/protobuf-cpp-3.9.2.tar.gz
	tar -xzf protobuf-cpp-3.9.2.tar.gz
	cd $PROTOBUF_V3_DIR
	if [[ "$ARCH" == "s390x" ]]; then
	    # XXX 3.9.2 is untested on s390x
	    wget $DEPENDENCIES_URL/protobuf-3.5.0-s390x.patch
	    patch -p1 < protobuf-3.5.0-s390x.patch
	    aclocal
	    automake
	fi
	if [ $OS != "Windows_NT" ]; then
		CPPFLAGS=-I$ZLIB_DIR LDFLAGS=-L$ZLIB_DIR ./configure --with-zlib --prefix=$PROTOBUF_V3_DIR/target
	else
		CPPFLAGS=-I$ZLIB_DIR LDFLAGS="-L$ZLIB_DIR -L/cygdrive/c/cygwin64/bin -L/bin" ./configure --with-zlib --prefix=$PROTOBUF_V3_DIR/target
	fi
	make -j $MAKE_JOBS
	make -j $MAKE_JOBS check
	make -j $MAKE_JOBS install
fi

if [ $OS != "Windows_NT" ]; then
	export GOPATH=$DEPENDENCIES/go
else
	# GOPATH can't be relative, so we need the absolute path starting with C:/
	# / is a link to C:/cygwin and can't be used
	# TODO: Provide GOPATH as an optional parameter to this script
	# The first path below works if you're building directly without using container with
	# standard cygwin install. The second path works if you're using windows-agent-builder

	# export GOPATH=C:/cygwin64$DEPENDENCIES/go
	export GOPATH=C:/cygwin64/code/agent/dependencies/go
fi
if [ ! -d "$GOPATH" ]; then
	mkdir $GOPATH
fi

OPENSSL_VER=1.0.2n
OPENSSL_EXT=tar.gz
OPENSSL_DIR=$DEPENDENCIES/openssl-$OPENSSL_VER
if [ ! -d "$OPENSSL_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/openssl-$OPENSSL_VER.$OPENSSL_EXT
	tar -xzf openssl-$OPENSSL_VER.$OPENSSL_EXT
	cd $OPENSSL_DIR
	./config shared --prefix=$OPENSSL_DIR/target
	make install
	cd ..
fi

CARES_VER=1.13.0
CARES_EXT=tar.gz
CARES_DIR=$DEPENDENCIES/c-ares-$CARES_VER
if [ ! -d "$CARES_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/c-ares-$CARES_VER.$CARES_EXT
	tar -xzf c-ares-$CARES_VER.$CARES_EXT
	cd $CARES_DIR
	./configure --prefix=$CARES_DIR/target
	make -j $MAKE_JOBS install
	cd ..
fi

if [ $OS != "Windows_NT" ]; then
	# Normally, grpc wants to use its own protobuf library, which it
	# expects to get via git submmodules. It mostly has support for using
	# a "system" protobuf/openssl instead, using pkg-config. The Makefile
	# does require one small change to properly set LDFLAGS to the
	# protobuf lib path returned by pkg-config. Hence the patch.
	GRPC_DIR=$DEPENDENCIES/grpc-1.24.3
	if [ ! -d "$GRPC_DIR" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/grpc-1.24.3.tar.gz
		tar -xzf grpc-1.24.3.tar.gz
		rm -rf grpc-1.24.3/third_party/zlib
		ln -s $ZLIB_DIR grpc-1.24.3/third_party/zlib
		if [[ "$ARCH" == "s390x" ]]; then
			# Boringssl build fails on s390x, rely on openssl instead
			rm -rf $GRPC_DIR/third_party/boringssl $GRPC_DIR/third_party/boringssl-with-bazel
		fi
		cd $GRPC_DIR
		wget $DEPENDENCIES_URL/grpc-1.1.4-Makefile.patch
		patch < grpc-1.1.4-Makefile.patch
		HAS_SYSTEM_ZLIB=false LDFLAGS=-static PATH=$PROTOBUF_V3_DIR/target/bin:$PATH PKG_CONFIG_PATH=$OPENSSL_DIR:$PROTOBUF_V3_DIR:$CARES_DIR make -j $MAKE_JOBS grpc_cpp_plugin static_cxx static_c
	fi
fi

POCO_VER=1.9.0
POCO_EXT=tar.gz
POCO_DIR=poco-$POCO_VER-all
POCO_ARCH=$POCO_DIR.$POCO_EXT
POCO_DIR=$DEPENDENCIES/$POCO_DIR
if [ ! -d "$POCO_DIR" ]; then
        cd $DEPENDENCIES
        wget $DEPENDENCIES_URL/$POCO_ARCH
 	tar -xzf $POCO_ARCH
	cd $POCO_DIR
	if [ $OS == "Windows_NT" ]; then
		# Need a change in build/config/CYGWIN to use SYSFLAGS = -D_GNU_SOURCE instead of -D_XOPEN_SOURCE
		# Ref: https://github.com/pocoproject/poco/commit/a9c4f31aa90da640867c753305dc8dcb6d4b58ea
		# This change is not included in 1.9.0, the latest released version of poco, so manually apply the change.
		# When we get a new poco release (say 1.9.1) with the above fix, we can switch to that release and get rid of the
		# manual hack.
		mv ./build/config/CYGWIN ./build/config/CYGWIN.orig
		sed 's/SYSFLAGS.*=.*-D_XOPEN_SOURCE.*/SYSFLAGS = -D_GNU_SOURCE/' ./build/config/CYGWIN.orig > ./build/config/CYGWIN
	fi
	./configure --prefix=./target --static --no-samples --no-tests --omit=Data,Data/MySQL,Data/ODBC,Data/SQLite,Zip,MongoDB,PageCompiler,PageCompiler/File2Page,Redis --include-path=$OPENSSL_DIR/target/include --cflags="-DPOCO_UTIL_NO_XMLCONFIGURATION -DPOCO_UTIL_NO_JSONCONFIGURATION"
	make -j $MAKE_JOBS install
	cd ..
fi

if [ $OS != "Windows_NT" ]; then
	GTEST_DIR=$DEPENDENCIES/gtest-1.7.0
	if [ ! -d "$GTEST_DIR" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/gtest-1.7.0.zip
		unzip gtest-1.7.0.zip
		cd $GTEST_DIR
		g++ -Iinclude -c fused-src/gtest/gtest-all.cc -o gtest-all.o
		g++ -Iinclude -c fused-src/gtest/gtest_main.cc -o gtest_main.o
		ar -rv libgtest.a gtest-all.o
		ar -rv libgtest_main.a gtest_main.o
	fi
fi

if [ ! -d "$DEPENDENCIES/simpleopt" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/simpleopt-3.6.zip
	unzip simpleopt-3.6.zip
fi

if [ $OS != "Windows_NT" ]; then
	CMAKE_DIR=$DEPENDENCIES/cmake-3.5.2
	if [ ! -d "$CMAKE_DIR" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/cmake-3.5.2.tar.gz
		tar -xzf cmake-3.5.2.tar.gz
		cd $CMAKE_DIR
		./bootstrap
		make -j $MAKE_JOBS
	fi

	BENCHMARK_DIR=$DEPENDENCIES/benchmark-1.5.0
	if [ ! -d "$BENCHMARK_DIR" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/benchmark-1.5.0.zip
		unzip benchmark-1.5.0.zip
		cd $BENCHMARK_DIR
		mkdir build
		cd build
		$CMAKE_DIR/bin/cmake -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DCMAKE_BUILD_TYPE=Release ..
		make -j $MAKE_JOBS
	fi
fi

if [[ "$ARCH" == "s390x" ]]; then
LUAJIT_DIR=$DEPENDENCIES/lua-5.1.5
if [ ! -d "$LUAJIT_DIR" ]; then
	cd $DEPENDENCIES
	wget https://www.lua.org/ftp/lua-5.1.5.tar.gz
	tar -xzf lua-5.1.5.tar.gz
	cd $LUAJIT_DIR
	make -j $MAKE_JOBS linux
fi
else
if [ $OS != "Windows_NT" ]; then
	LUAJIT_NAME=LuaJIT-2.0.3
else
	LUAJIT_NAME=LuaJIT-2.0.5
fi
LUAJIT_DIR=$DEPENDENCIES/$LUAJIT_NAME

if [ ! -d "$LUAJIT_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/$LUAJIT_NAME.tar.gz
	tar -xzf $LUAJIT_NAME.tar.gz
	cd $LUAJIT_DIR
	if [ $OS != "Windows_NT" ]; then
		make -j $MAKE_JOBS
	else
		make -j $MAKE_JOBS BUILDMODE=static
	fi
fi
fi

CURL_NAME=curl-7.61.0
CURL_EXT=tar.bz2
CURL_DIR=$DEPENDENCIES/$CURL_NAME
if [ ! -d "$CURL_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/$CURL_NAME.$CURL_EXT
	tar -xjf $CURL_NAME.$CURL_EXT
	cd $CURL_DIR
	./configure --disable-shared  \
		--enable-optimize     \
		--disable-curldebug   \
		--disable-rt          \
		--enable-http         \
		--disable-ftp         \
		--disable-file        \
		--disable-ldap        \
		--disable-ldaps       \
		--disable-rtsp        \
		--disable-telnet      \
		--disable-tftp        \
		--disable-pop3        \
		--disable-imap        \
		--disable-smb         \
		--disable-smtp        \
		--disable-gopher      \
		--disable-sspi        \
		--disable-ntlm-wb     \
		--disable-tls-srp     \
		--without-winssl      \
		--without-darwinssl   \
		--with-ssl=$OPENSSL_DIR/target \
		--without-polarssl    \
		--without-cyassl      \
		--without-nss         \
		--without-axtls       \
		--without-ca-path     \
		--without-ca-bundle   \
		--without-libmetalink \
		--without-librtmp     \
		--without-winidn      \
		--without-libidn      \
		--without-nghttp2     \
		--enable-ares=$CARES_DIR/target
	make -j $MAKE_JOBS
fi

B64_NAME=libb64-1.2
B64_EXT=src.zip
B64_DIR=$DEPENDENCIES/$B64_NAME
if [ ! -d "$B64_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/$B64_NAME.$B64_EXT
	unzip $B64_NAME.$B64_EXT
	cd $B64_DIR
	make -j $MAKE_JOBS
fi

# On s390x we'll rely on Suse's jdk 1.7.0 for now
if [ $OS != "Windows_NT" ]; then
	if [[ "$ARCH" == "s390x" ]]; then
		JAVA_DIR=/usr/lib64/jvm/java-1.7.0-openjdk-1.7.0
	else
		JAVA_DIR=$DEPENDENCIES/jdk1.7.0_75
		if [ ! -d "$JAVA_DIR" ]; then
			cd $DEPENDENCIES
			if [[ $ARCH == "x86_64" ]]; then
				TARFILE=jdk-7u75-linux-x64.tar.bz2
			else
				TARFILE=jdk-7u75-linux-i586.tar.bz2
			fi
			wget $DEPENDENCIES_URL/$TARFILE
			tar -xjf $TARFILE
		fi
	fi
	MAVEN_DIR=$DEPENDENCIES/apache-maven-3.2.5
	if [ ! -d "$MAVEN_DIR" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/apache-maven-3.2.5-bin.tar.gz
		tar -xzf apache-maven-3.2.5-bin.tar.gz
	fi
fi

BOOST_DIR=$DEPENDENCIES/boost_1_57_0
if [ ! -d "$BOOST_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/boost_1_57_0.tar.bz2
	tar xfj boost_1_57_0.tar.bz2
fi

YAMLCPP_DIR=$DEPENDENCIES/yaml-cpp-0.5.1
if [ ! -d "$YAMLCPP_DIR" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/yaml-cpp-0.5.1.tar.gz
	tar xfz yaml-cpp-0.5.1.tar.gz
	cd $YAMLCPP_DIR
	mkdir build
	cd build
	if [ $OS != "Windows_NT" ]; then
		BOOST_ROOT=$BOOST_DIR $CMAKE_DIR/bin/cmake -DCMAKE_INSTALL_PREFIX=$YAMLCPP_DIR/target -DYAML_CPP_BUILD_CONTRIB=OFF ..
	else
		BOOST_ROOT=$BOOST_DIR /usr/bin/cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$YAMLCPP_DIR/target -DYAML_CPP_BUILD_CONTRIB=OFF ..
	fi
	make -j $MAKE_JOBS install
fi

SCONS_DIR=$DEPENDENCIES/scons-2.3.4
if [ ! -d "${SCONS_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/scons-2.3.4.tar.gz
	tar xfz scons-2.3.4.tar.gz
fi

if [ $OS != "Windows_NT" ]; then
	PYTHON37_VER=3.7.3
	PYTHON37_EXT=tgz
	PYTHON37_DIR=$DEPENDENCIES/Python-$PYTHON37_VER
	if [ ! -d "${PYTHON37_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/Python-$PYTHON37_VER.$PYTHON37_EXT
		tar xfz Python-$PYTHON37_VER.$PYTHON37_EXT
		cd $PYTHON37_DIR
		echo "zlib zlibmodule.c -I${ZLIB_DIR}/ -L${ZLIB_DIR}/ -lz" >> Modules/Setup.dist
		./configure CPPFLAGS="-DUSE_SSL -I${OPENSSL_DIR}/target/include" LDFLAGS="-L${OPENSSL_DIR}/target/lib -Wl,-rpath=${OPENSSL_DIR}/target/lib" --prefix=$PYTHON37_DIR/target --with-ensurepip=install --enable-unicode=ucs4
		make -j $MAKE_JOBS
		make -j $MAKE_JOBS install
	fi

	PYTHON36_VER=3.6.9
	PYTHON36_EXT=tgz
	PYTHON36_DIR=$DEPENDENCIES/Python-$PYTHON36_VER
	if [ ! -d "${PYTHON36_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/Python-$PYTHON36_VER.$PYTHON36_EXT
		tar xfz Python-$PYTHON36_VER.$PYTHON36_EXT
		cd $PYTHON36_DIR
		echo "zlib zlibmodule.c -I${ZLIB_DIR}/ -L${ZLIB_DIR}/ -lz" >> Modules/Setup.dist
		./configure CPPFLAGS="-DUSE_SSL -I${OPENSSL_DIR}/target/include" LDFLAGS="-L${OPENSSL_DIR}/target/lib -Wl,-rpath=${OPENSSL_DIR}/target/lib" --prefix=$PYTHON36_DIR/target --with-ensurepip=install --enable-unicode=ucs4
		make -j $MAKE_JOBS
		make -j $MAKE_JOBS install
	fi

	PYTHON35_VER=3.5.9
	PYTHON35_EXT=tgz
	PYTHON35_DIR=$DEPENDENCIES/Python-$PYTHON35_VER
	if [ ! -d "${PYTHON35_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/Python-$PYTHON35_VER.$PYTHON35_EXT
		tar xfz Python-$PYTHON35_VER.$PYTHON35_EXT
		cd $PYTHON35_DIR
		echo "zlib zlibmodule.c -I${ZLIB_DIR}/ -L${ZLIB_DIR}/ -lz" >> Modules/Setup.dist
		./configure CPPFLAGS="-DUSE_SSL -I${OPENSSL_DIR}/target/include" LDFLAGS="-L${OPENSSL_DIR}/target/lib -Wl,-rpath=${OPENSSL_DIR}/target/lib" --prefix=$PYTHON35_DIR/target --with-ensurepip=install --enable-unicode=ucs4
		make -j $MAKE_JOBS
		make -j $MAKE_JOBS install
	fi

	PYTHON_VER=2.7.16
	PYTHON_EXT=tgz
	PYTHON_DIR=$DEPENDENCIES/Python-$PYTHON_VER
	if [ ! -d "${PYTHON_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/Python-$PYTHON_VER.$PYTHON_EXT
		tar xfz Python-$PYTHON_VER.$PYTHON_EXT
		cd $PYTHON_DIR
		echo "zlib zlibmodule.c -I${ZLIB_DIR}/ -L${ZLIB_DIR}/ -lz" >> Modules/Setup.dist
		./configure CPPFLAGS="-DUSE_SSL -I${OPENSSL_DIR}/target/include" LDFLAGS="-L${OPENSSL_DIR}/target/lib -Wl,-rpath=${OPENSSL_DIR}/target/lib" --prefix=$PYTHON_DIR/target --with-ensurepip=install --enable-unicode=ucs4
		make -j $MAKE_JOBS
		make -j $MAKE_JOBS install
	fi

	PYTHON26_VER=2.6.9
	PYTHON26_EXT=tgz
	PYTHON26_DIR=$DEPENDENCIES/Python-$PYTHON26_VER
	if [ ! -d "${PYTHON26_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/Python-$PYTHON26_VER.$PYTHON26_EXT
		tar xfz Python-$PYTHON26_VER.$PYTHON26_EXT
		cd $PYTHON26_DIR
		echo "zlib zlibmodule.c -I${ZLIB_DIR}/ -L${ZLIB_DIR}/ -lz" >> Modules/Setup.dist
		./configure CPPFLAGS="-DUSE_SSL -I${OPENSSL_DIR}/target/include" LDFLAGS="-L${OPENSSL_DIR}/target/lib -Wl,-rpath=${OPENSSL_DIR}/target/lib" --prefix=$PYTHON26_DIR/target --enable-unicode=ucs4
		make -j $MAKE_JOBS
		make -j $MAKE_JOBS install
		wget $DEPENDENCIES_URL/get-pip.py
		echo "setuptools==36.8.0" > pip-reqs.txt
		echo "wheel==0.29.0" >> pip-reqs.txt
		./target/bin/python get-pip.py --no-setuptools --no-wheel -r pip-reqs.txt
	fi

	if [ -z $STATSITE_VERSION ]; then
	  STATSITE_VERSION=0.7.0-sysdig6
	fi
	STATSITE_DIR=$DEPENDENCIES/statsite-private-$STATSITE_VERSION
	if [ ! -d "${STATSITE_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/statsite-private-$STATSITE_VERSION.zip
		unzip statsite-private-$STATSITE_VERSION.zip
		cd $STATSITE_DIR
		$PYTHON_DIR/target/bin/python $SCONS_DIR/script/scons
	fi

	POSTGRES_DIR=$DEPENDENCIES/postgresql-9.4.15
	if [ ! -d "${POSTGRES_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/postgresql-9.4.15.tar.bz2
		tar xfj postgresql-9.4.15.tar.bz2
		cd $POSTGRES_DIR
		./configure --prefix=$POSTGRES_DIR/target --without-readline --without-zlib
		make -j $MAKE_JOBS
		make -j $MAX_PARALLIEISM -C src/bin install
		make -j $MAKE_JOBS -C src/include install
		make -j $MAKE_JOBS -C src/interfaces install
	fi

	GPERFTOOLS_DIR=$DEPENDENCIES/gperftools-2.5
	if [ ! -d "${GPERFTOOLS_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/gperftools-2.5.tar.gz
		tar xfz gperftools-2.5.tar.gz
		cd $GPERFTOOLS_DIR
		./configure --prefix=${GPERFTOOLS_DIR}/target --enable-emergency-malloc --disable-libunwind
		make -j $MAKE_JOBS
		make -j $MAKE_JOBS install
	fi
fi

# Falco Engine dependencies
LPEG_DIR=$DEPENDENCIES/lpeg-1.0.0
if [ ! -d "${LPEG_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/lpeg-1.0.0.tar.gz
	tar -xzf lpeg-1.0.0.tar.gz
	cd $LPEG_DIR
	LUA_INCLUDE=${LUAJIT_DIR}/src "${ROOT_SOURCEDIR}/oss-falco/scripts/build-lpeg.sh" "${LPEG_DIR}/target"
fi

LIBYAML_DIR=$DEPENDENCIES/libyaml-0.1.7
if [ ! -d "${LIBYAML_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/libyaml-0.1.7.tar.gz
	tar -xzf libyaml-0.1.7.tar.gz
	cd $LIBYAML_DIR
	./bootstrap && ./configure --prefix=$LIBYAML_DIR/target
	make -j $MAKE_JOBS
	make -j $MAKE_JOBS install
fi

LYAML_DIR=$DEPENDENCIES/lyaml-release-v6.0
if [ ! -d "${LYAML_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/lyaml-release-v6.0.tar.gz
	tar -xzf lyaml-release-v6.0.tar.gz
	cd $LYAML_DIR
	CONFLUA=${LUAJIT_DIR}/src/lua
	if [ -e "${CONFLUA}jit" ]; then
		CONFLUA="${CONFLUA}jit"
	fi
	LD_LIBRARY_PATH="${LIBYAML_DIR}/target/lib" ./configure --prefix=$LYAML_DIR/target --enable-static LIBS=-L${LIBYAML_DIR}/target/lib CFLAGS=-I${LIBYAML_DIR}/target/include CPPFLAGS=-I${LIBYAML_DIR}/target/include LUA_INCLUDE=-I${LUAJIT_DIR}/src LUA=${CONFLUA}
	make -j $MAKE_JOBS
	make -j $MAKE_JOBS install
	sh -c "cp -R ${LYAML_DIR}/lib/* ${ROOT_SOURCEDIR}/oss-falco/userspace/engine/lua"
fi

KUBECTL_BINARY=$DEPENDENCIES/kubectl-1.9.6
if [ ! -f "${KUBECTL_BINARY}" ]; then
	cd $DEPENDENCIES
	wget https://storage.googleapis.com/kubernetes-release/release/v1.9.6/bin/linux/amd64/kubectl -O $KUBECTL_BINARY
fi

KUBE_BENCH_DIR=$DEPENDENCIES/kube-bench-0.0.24.2
if [ ! -d "${KUBE_BENCH_DIR}" ]; then
	cd $DEPENDENCIES
	wget $DEPENDENCIES_URL/kube-bench-0.0.24.2.tar.gz
	tar -xzf kube-bench-0.0.24.2.tar.gz
fi

if [ $OS == "Windows_NT" ]; then
	WINHAL_DIR=$DEPENDENCIES/dragent-win-hal-1.0
	if [ ! -d "${WINHAL_DIR}" ]; then
		cd $DEPENDENCIES
		wget $DEPENDENCIES_URL/dragent-win-hal-1.0.zip
		unzip dragent-win-hal-1.0.zip
	fi
fi

if [ -z "$AGENT_VERSION" ]; then
	AGENT_VERSION="0.1.1dev"
fi

if [ -z "$BUILD_DRIVER" ]; then
	BUILD_DRIVER=ON
fi

if [ -z "$BUILD_BPF" ]; then
	BUILD_BPF=OFF
fi

if [ -z "$BUILD_WARNINGS_AS_ERRORS" ]; then
	BUILD_WARNINGS_AS_ERRORS=ON
fi

if [ -z "$AGENT_BUILD_DATE" ]; then
	AGENT_BUILD_DATE="`date`"
fi

if [ -z "$ONLY_DEPS" ]; then
	AGENT_BUILD_DIR=$WORKDIR/agent/build
	mkdir -p $AGENT_BUILD_DIR/debug
	mkdir -p $AGENT_BUILD_DIR/release
	mkdir -p $AGENT_BUILD_DIR/debug-internal
	mkdir -p $AGENT_BUILD_DIR/release-internal
	mkdir -p $AGENT_BUILD_DIR/debug-internal-code-coverage

	if [ $OS != "Windows_NT" ]; then
		if [ -z "$BUILD_DEB_ONLY" ]; then
			BUILD_DEB_ONLY="OFF"
		fi

		cd $AGENT_BUILD_DIR/debug
		$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DAGENT_BUILD_COMMIT="${AGENT_BUILD_COMMIT:-}" -DAGENT_BUILD_DATE="$AGENT_BUILD_DATE" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_BPF} -DPACKAGE_DEB_ONLY=$BUILD_DEB_ONLY -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/opt/draios}" -DCOMBINED_PACKAGE=${COMBINED_PACKAGE:-ON} -DBUILD_WARNINGS_AS_ERRORS=${BUILD_WARNINGS_AS_ERRORS} $AGENT_SOURCEDIR
		cd $AGENT_BUILD_DIR/release
		$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=Release -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DAGENT_BUILD_COMMIT="${AGENT_BUILD_COMMIT:-}" -DAGENT_BUILD_DATE="$AGENT_BUILD_DATE" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_BPF} -DPACKAGE_DEB_ONLY=$BUILD_DEB_ONLY -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/opt/draios}" -DCOMBINED_PACKAGE=${COMBINED_PACKAGE:-ON} -DBUILD_WARNINGS_AS_ERRORS=${BUILD_WARNINGS_AS_ERRORS} $AGENT_SOURCEDIR
		cd $AGENT_BUILD_DIR/debug-internal
		$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=DebugInternal -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DAGENT_BUILD_COMMIT="${AGENT_BUILD_COMMIT:-}" -DAGENT_BUILD_DATE="$AGENT_BUILD_DATE" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_BPF} -DPACKAGE_DEB_ONLY=$BUILD_DEB_ONLY -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/opt/draios}" -DCOMBINED_PACKAGE=${COMBINED_PACKAGE:-ON} -DBUILD_WARNINGS_AS_ERRORS=${BUILD_WARNINGS_AS_ERRORS} $AGENT_SOURCEDIR
		cd $AGENT_BUILD_DIR/release-internal
		$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=ReleaseInternal -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DAGENT_BUILD_COMMIT="${AGENT_BUILD_COMMIT:-}" -DAGENT_BUILD_DATE="$AGENT_BUILD_DATE" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_BPF} -DPACKAGE_DEB_ONLY=$BUILD_DEB_ONLY -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/opt/draios}" -DCOMBINED_PACKAGE=${COMBINED_PACKAGE:-ON} -DBUILD_WARNINGS_AS_ERRORS=${BUILD_WARNINGS_AS_ERRORS} $AGENT_SOURCEDIR
		cd $AGENT_BUILD_DIR/debug-internal-code-coverage
		$CMAKE_DIR/bin/cmake -DCMAKE_BUILD_TYPE=DebugInternalCodeCoverage -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DAGENT_BUILD_COMMIT="${AGENT_BUILD_COMMIT:-}" -DAGENT_BUILD_DATE="$AGENT_BUILD_DATE" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_BPF} -DPACKAGE_DEB_ONLY=$BUILD_DEB_ONLY -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/opt/draios}" -DCOMBINED_PACKAGE=${COMBINED_PACKAGE:-ON} -DBUILD_WARNINGS_AS_ERRORS=${BUILD_WARNINGS_AS_ERRORS} $AGENT_SOURCEDIR
	else
		# In Windows, we don't build the cointerface protobufs, and therefore we just create
		# two empty placeholder files here
		mkdir -p $AGENT_BUILD_DIR/debug/userspace/draiosproto/
		mkdir -p $AGENT_BUILD_DIR/release/userspace/draiosproto/
		echo "" > $AGENT_BUILD_DIR/debug/userspace/draiosproto/sdc_internal.pb.cc
		echo "" > $AGENT_BUILD_DIR/release/userspace/draiosproto/sdc_internal.pb.cc
		echo "" > $AGENT_BUILD_DIR/debug/userspace/draiosproto/sdc_internal.grpc.pb.cc
		echo "" > $AGENT_BUILD_DIR/release/userspace/draiosproto/sdc_internal.grpc.pb.cc

		# Turn off warnings as errors option for Windows
		# TODO: Fix warnings and then turn it on
		BUILD_WARNINGS_AS_ERRORS=OFF
		cd $AGENT_BUILD_DIR/debug
		/usr/bin/cmake -G"Unix Makefiles" -DCYGWIN=TRUE -DCMAKE_BUILD_TYPE=Debug -DDRAGENT_WINHAL_DIR=$WINHAL_DIR -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/opt/draios}" $AGENT_SOURCEDIR
		cd $AGENT_BUILD_DIR/release
		/usr/bin/cmake -G"Unix Makefiles" -DCYGWIN=TRUE -DCMAKE_BUILD_TYPE=Release -DDRAGENT_WINHAL_DIR=$WINHAL_DIR -DDRAIOS_DEPENDENCIES_DIR=$DEPENDENCIES -DJAVA_HOME=$JAVA_DIR -DAGENT_VERSION="$AGENT_VERSION" -DAGENT_BUILD_COMMIT="${AGENT_BUILD_COMMIT:-}" -DAGENT_BUILD_DATE="$AGENT_BUILD_DATE" -DSTATSITE_VERSION=$STATSITE_VERSION -DBUILD_DRIVER=${BUILD_DRIVER} -DBUILD_BPF=${BUILD_BPF} -DBUILD_WARNINGS_AS_ERRORS=${BUILD_WARNINGS_AS_ERRORS} -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX:-/opt/draios}" $AGENT_SOURCEDIR

	fi
fi
