FROM s390x/debian:11.0

MAINTAINER Sysdig <support@sysdig.com>

ENV SYSDIG_REPOSITORY dev

ENV SYSDIG_HOST_ROOT /host

ENV AGENT_VERSION 0.1.1dev

ENV HOME /root

RUN cp /etc/skel/.bashrc /root && cp /etc/skel/.profile /root

RUN apt-get update
RUN apt-get install -y gnupg2

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key 7638D0442B90D010
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key CBF8D6FD518E17E1

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
	bash-completion \
	bc \
	curl \
	gnupg2 \
	ca-certificates \
	gcc \
	gcc-4.9 \
	libelf1 \
	openjdk-11-jre-headless \
	python \
	dkms

RUN apt-get install -y \
	python3

RUN apt-get install -y --no-install-recommends \
	libyaml-0-2 \
	python3-lib2to3 \
	python3-certifi \
	python3-distutils \
	python3-pip \
	python3-dev

RUN pip install posix-ipc

# Since our base Debian image ships with GCC 5.0 which breaks older kernels, revert the
# default to gcc-4.9. Also, since some customers use some very old distributions whose kernel
# makefile is hardcoded for gcc-4.6 or so (e.g. Debian Wheezy), we pretend to have gcc 4.6/4.7
# by symlinking it to 4.9

RUN rm -rf /usr/bin/gcc \
 && ln -s /usr/bin/gcc-4.9 /usr/bin/gcc \
 && ln -s /usr/bin/gcc-4.9 /usr/bin/gcc-4.8 \
 && ln -s /usr/bin/gcc-4.9 /usr/bin/gcc-4.7 \
 && ln -s /usr/bin/gcc-4.9 /usr/bin/gcc-4.6

RUN rm -rf /usr/bin/clang \
 && rm -rf /usr/bin/llc \
 && ln -s /usr/bin/clang-7 /usr/bin/clang \
 && ln -s /usr/bin/llc-7 /usr/bin/llc

RUN ln -s $SYSDIG_HOST_ROOT/lib/modules /lib/modules

ADD draios-${AGENT_VERSION}-s390x-agent.deb /
RUN dpkg -i /draios-${AGENT_VERSION}-s390x-agent.deb
COPY ./docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
