FROM debian:11.0

MAINTAINER Sysdig <support@sysdig.com>

ENV SYSDIG_REPOSITORY dev

ENV SYSDIG_HOST_ROOT /host

ENV AGENT_VERSION 0.1.1dev

ENV HOME /root

RUN cp /etc/skel/.bashrc /root && cp /etc/skel/.profile /root

RUN apt-get update
RUN apt-get install -y gnupg2

# RUN echo "deb http://httpredir.debian.org/debian jessie main" > /etc/apt/sources.list.d/jessie.list
# RUN apt-key adv --keyserver pgpkeys.mit.edu --recv-key 7638D0442B90D010
# RUN apt-key adv --keyserver pgpkeys.mit.edu:80 --recv-key 7638D0442B90D010
# RUN apt-key adv --keyserver pgpkeys.mit.edu --recv-key CBF8D6FD518E17E1
# RUN apt-key adv --keyserver pgpkeys.mit.edu:80 --recv-key CBF8D6FD518E17E1
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key 7638D0442B90D010
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key CBF8D6FD518E17E1

RUN apt-get update

RUN apt-get install -y --no-install-recommends dpkg

RUN apt list | grep gcc

RUN apt-get install -y --no-install-recommends \
	bash-completion \
	bc \
	clang \
	curl \
	ca-certificates \
	gcc \
	libelf1 \
	python \
	dkms

RUN apt-get install -y \
	python3

RUN apt-get install -y --no-install-recommends \
	libyaml-0-2 \
	python3-lib2to3 \
	python3-certifi \
	python3-distutils

RUN apt-get install -y --no-install-recommends \
	libyaml-0-2 \
	python3-lib2to3 \
	python3-certifi \
	python3-distutils \
	python3-pip \
	python3-dev

RUN apt-get install -y \
	llvm

RUN pip install posix-ipc

RUN ln -s $SYSDIG_HOST_ROOT/lib/modules /lib/modules

RUN gcc --version

ADD draios-${AGENT_VERSION}-aarch64-agent.deb /
# RUN dpkg --add-architecture aarch64
RUN dpkg -i /draios-${AGENT_VERSION}-aarch64-agent.deb
COPY ./docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
