#!/bin/sh
set -e

if [ -x "/etc/init.d/dragent" ]; then
        update-rc.d dragent defaults >/dev/null
fi

if [ -x "/etc/init.d/dragent" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d dragent start || exit $?
        else
                /etc/init.d/dragent start || exit $?
        fi
fi
