#!/bin/sh
set -e

CONFIG_FILE=/opt/draios/etc/dragent.yaml
OLD_CONFIG_FILE=/opt/draios/bin/dragent.properties

if [ ! -e $CONFIG_FILE ]; then
	if grep -q ^customerid $OLD_CONFIG_FILE > /dev/null 2>&1; then
		CUSTOMERID=`grep ^customerid $OLD_CONFIG_FILE|tr -d ' '|cut -d'=' -f2`
		echo "customerid: $CUSTOMERID" >> $CONFIG_FILE
	fi
	if grep -q ^ui.tags $OLD_CONFIG_FILE > /dev/null 2>&1; then
		TAGS=`grep ^ui.tags $OLD_CONFIG_FILE|tr -d ' '|cut -d'=' -f2`
		echo "tags: $TAGS" >> $CONFIG_FILE
	fi
	if grep -q ^remotefs.enabled $OLD_CONFIG_FILE > /dev/null 2>&1; then
		REMOTEFS=`grep ^remotefs.enabled $OLD_CONFIG_FILE|tr -d ' '|cut -d'=' -f2`
		echo "remotefs: $REMOTEFS" >> $CONFIG_FILE
	fi
	if grep -q ^protocols.enabled $OLD_CONFIG_FILE > /dev/null 2>&1; then
		PROTOCOLS=`grep ^protocols.enabled $OLD_CONFIG_FILE|tr -d ' '|cut -d'=' -f2`
		echo "protocols: $PROTOCOLS" >> $CONFIG_FILE
	fi
fi

if [ -x "/etc/init.d/dragent" ]; then
        update-rc.d dragent defaults >/dev/null
fi

if [ -x "/etc/init.d/dragent" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d dragent start || exit $?
        else
                /etc/init.d/dragent start || exit $?
        fi
fi
