#!/bin/sh
set -e

if [ -x "/etc/init.d/dragent" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d dragent stop || exit $?
        else
                /etc/init.d/dragent stop || exit $?
        fi
fi
