#!/bin/sh
set -e

if [ -x "/etc/init.d/dragent" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d dragent stop || exit $?
        else
                /etc/init.d/dragent stop || exit $?
        fi
fi

# Clean all generated Python bytecode
find /opt/draios/lib -iname "*.pyc" -delete > /dev/null 2>&1
find /opt/draios/lib -iname "*.pyo" -delete > /dev/null 2>&1