FROM {{ p.base_docker_image }}

MAINTAINER Sysdig <support@sysdig.com>

{% if p.include_agent_package is defined %}
ENV SYSDIG_REPOSITORY {{ p.sysdig_repository }}

{% endif %}
ENV SYSDIG_BUILD_KERNEL_MODULE {{ p.build_kernel_module }}

ENV SYSDIG_LAUNCH_DRAGENT {{ p.launch_dragent }}

{% if p.build_kernel_module and not p.include_agent_package is defined %}
COPY ./sysdigcloud-probe-loader /opt/draios/bin/

{% endif %}
{% if p.agent_version is defined %}
ENV SYSDIG_VERSION {{ p.agent_version }}

{% endif %}
ENV SYSDIG_HOST_ROOT /host

{% if p.build_kernel_module == 1 %}
{% if p.include_agent_package == "local" %}
ENV AGENT_VERSION 0.1.1dev

{% endif %}
ENV HOME /root

{% endif %}

{% if p.include_agent_package == "apt" %}
ADD http://download.draios.com/apt-draios-priority /etc/apt/preferences.d/

{% endif %}
{% if p.backports_debian_release == "jessie-backports" %}
RUN echo "deb http://ftp.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list

{% endif %}
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y --no-install-recommends \
	bash-completion \
	curl \
	ca-certificates \
	bzip2 \
	iproute2 \
	procps \
{% if p.build_kernel_module %}
	bc \
	clang-7 \
	dkms \
	gcc \
	gcc-6 \
	gcc-5 \
	libc6-dev \
	libelf-dev \
	libelf1 \
	llvm-7 \
	xz-utils \
{% endif %}
{% if p.include_agent_package is defined %}
	gnupg2 \
	python \
 && apt-get install -y --no-install-recommends -t {{ p.backports_debian_release }} openjdk-8-jre-headless docker.io \
{% endif %}
 && rm -rf /var/lib/apt/lists/*

{% if p.build_kernel_module %}
# Since our base Debian image ships with GCC 7 which breaks older kernels, revert the
# default to gcc-5.
# Older distributions of Debian use hardcoded versions of gcc in the kernel Makefile. We
# pretend to have them by creating symlinks to our default gcc.
# 4.9 is required for Debian Jessie+backports and 4.8 is required for Debian Jessie.
RUN rm -rf /usr/bin/gcc && ln -s /usr/bin/gcc-5 /usr/bin/gcc \
 && ln -s /usr/bin/gcc /usr/bin/gcc-4.9 \
 && ln -s /usr/bin/gcc /usr/bin/gcc-4.8

RUN rm -rf /usr/bin/clang \
 && rm -rf /usr/bin/llc \
 && ln -s /usr/bin/clang-7 /usr/bin/clang \
 && ln -s /usr/bin/llc-7 /usr/bin/llc

{% endif %}
{% if p.include_agent_package == "apt" %}
RUN curl -s https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public | apt-key add - \
 && curl -s -o /etc/apt/sources.list.d/draios.list http://download.draios.com/$SYSDIG_REPOSITORY/deb/draios.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends draios-agent \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

{% endif %}
{% if p.build_kernel_module %}
RUN rm -df /lib/modules \
 && ln -s $SYSDIG_HOST_ROOT/lib/modules /lib/modules

# debian:unstable head contains binutils 2.31, which generates
# binaries that are incompatible with kernels < 4.16. So manually
# forcibly install binutils 2.30-22 instead.
RUN curl -s -o binutils_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/binutils_2.30-22_amd64.deb \
 && curl -s -o libbinutils_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/libbinutils_2.30-22_amd64.deb \
 && curl -s -o binutils-x86-64-linux-gnu_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/binutils-x86-64-linux-gnu_2.30-22_amd64.deb \
 && curl -s -o binutils-common_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/binutils-common_2.30-22_amd64.deb \
 && dpkg -i *binutils*.deb \
 && rm -f *binutils*.deb

{% endif %}
{% if p.include_agent_package == "local" %}
ADD draios-${AGENT_VERSION}-x86_64-agent.deb /
RUN dpkg -i /draios-${AGENT_VERSION}-x86_64-agent.deb

{% endif %}
COPY ./docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]

