FROM {{ p.base_docker_image }}

MAINTAINER Sysdig <support@sysdig.com>

{% if p.include_agent_package is defined %}
ENV SYSDIG_REPOSITORY {{ p.sysdig_repository }}

{% endif %}
ENV SYSDIG_BUILD_KERNEL_MODULE {{ p.build_kernel_module }}

ENV SYSDIG_LAUNCH_DRAGENT {{ p.launch_dragent }}

{% if p.build_kernel_module and not p.include_agent_package is defined %}
COPY ./sysdigcloud-probe-loader /opt/draios/bin/

{% endif %}
{% if p.agent_version is defined %}
ENV SYSDIG_VERSION {{ p.agent_version }}

{% endif %}
ENV SYSDIG_HOST_ROOT /host

{% if p.build_kernel_module == 1 %}
{% if p.include_agent_package == "local" %}
ENV AGENT_VERSION 0.1.1dev

{% endif %}
ENV HOME /root

{% endif %}

{% if p.include_agent_package == "apt" %}
ADD http://download.draios.com/apt-draios-priority /etc/apt/preferences.d/

{% endif %}
{% if p.backports_debian_release == "jessie-backports" %}
RUN echo "deb http://ftp.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list

{% endif %}
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y --no-install-recommends \
# current bash-completion is a security hole
# SMAGENT-1222
#        bash-completion
	curl \
	ca-certificates \
	bzip2 \
	iproute2 \
	procps \
{% if p.build_kernel_module %}
	bc \
	clang-7 \
	dkms \
	gcc \
	gcc-6 \
	libc6-dev \
	libelf-dev \
	libelf1 \
	llvm-7 \
	xz-utils \
{% endif %}
{% if p.include_agent_package is defined %}
	gnupg2 \
	python \
 && apt-get install -y --no-install-recommends -t {{ p.backports_debian_release }} docker.io \
{% endif %}
 && rm -rf /var/lib/apt/lists/*

{% if p.build_kernel_module %}
# gcc 5 is no longer included in debian unstable, but we need it to
# build centos kernels, which are 3.x based and explicitly want a gcc
# version 3, 4, or 5 compiler. So grab copies we've saved from debian
# snapshots with the prefix https://snapshot.debian.org/archive/debian/20190122T000000Z.

RUN curl -o cpp-5_5.5.0-12_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/cpp-5_5.5.0-12_amd64.deb \
 && curl -o gcc-5-base_5.5.0-12_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/gcc-5-base_5.5.0-12_amd64.deb \
 && curl -o gcc-5_5.5.0-12_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/gcc-5_5.5.0-12_amd64.deb \
 && curl -o libasan2_5.5.0-12_amd64.deb	https://s3.amazonaws.com/download.draios.com/dependencies/libasan2_5.5.0-12_amd64.deb \
 && curl -o libgcc-5-dev_5.5.0-12_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/libgcc-5-dev_5.5.0-12_amd64.deb \
 && curl -o libisl15_0.18-4_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/libisl15_0.18-4_amd64.deb \
 && curl -o libmpx0_5.5.0-12_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/libmpx0_5.5.0-12_amd64.deb \
 && dpkg -i cpp-5_5.5.0-12_amd64.deb gcc-5-base_5.5.0-12_amd64.deb gcc-5_5.5.0-12_amd64.deb libasan2_5.5.0-12_amd64.deb libgcc-5-dev_5.5.0-12_amd64.deb libisl15_0.18-4_amd64.deb libmpx0_5.5.0-12_amd64.deb \
 && rm -f cpp-5_5.5.0-12_amd64.deb gcc-5-base_5.5.0-12_amd64.deb gcc-5_5.5.0-12_amd64.deb libasan2_5.5.0-12_amd64.deb libgcc-5-dev_5.5.0-12_amd64.deb libisl15_0.18-4_amd64.deb libmpx0_5.5.0-12_amd64.deb
{% endif %}

{% if p.include_agent_package is defined %}
#
# Download, verify, and install a AdoptOpenJDK's JRE
#
RUN JAVA_VERSION_MAJOR=8 \
 && JAVA_VERSION_MINOR=192 \
 && JAVA_VERSION_BUILD=12 \
 && JRE_ARCHIVE_FILE="/tmp/jre.tgz" \
 && curl -jksSlL -o "${JRE_ARCHIVE_FILE}" \
        https://github.com/AdoptOpenJDK/openjdk${JAVA_VERSION_MAJOR}-binaries/releases/download/jdk${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/OpenJDK${JAVA_VERSION_MAJOR}U-jre_x64_linux_hotspot_${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}b${JAVA_VERSION_BUILD}.tar.gz \
 && JAVA_PACKAGE_SHA256=$(curl -sSlL https://github.com/AdoptOpenJDK/openjdk${JAVA_VERSION_MAJOR}-binaries/releases/download/jdk${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/OpenJDK${JAVA_VERSION_MAJOR}U-jre_x64_linux_hotspot_${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}b${JAVA_VERSION_BUILD}.tar.gz.sha256.txt | awk '{ print $1 }') \
 && echo "${JAVA_PACKAGE_SHA256}  ${JRE_ARCHIVE_FILE}" > ${JRE_ARCHIVE_FILE}.sha256 \
 && sha256sum -c ${JRE_ARCHIVE_FILE}.sha256 \
 && tar -C /opt -zxf "${JRE_ARCHIVE_FILE}" \
 && rm "${JRE_ARCHIVE_FILE}" "${JRE_ARCHIVE_FILE}.sha256" \
 && JAVA_INSTALL_DIR="/opt/jdk${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}-jre" \
 && rm -r "${JAVA_INSTALL_DIR}/man" \
 && chown -R root:root "${JAVA_INSTALL_DIR}" \
 && (cd "${JAVA_INSTALL_DIR}/bin" && for i in $(ls); do ln -sf "${JAVA_INSTALL_DIR}/bin/$i" "/etc/alternatives/$i"; ln -sf "/etc/alternatives/$i" "/usr/bin/$i"; done) \
 && true
{% endif %}

{% if p.build_kernel_module %}
# Since our base Debian image ships with GCC 7 which breaks older kernels, revert the
# default to gcc-5.
# Older distributions of Debian use hardcoded versions of gcc in the kernel Makefile. We
# pretend to have them by creating symlinks to our default gcc.
# 4.9 is required for Debian Jessie+backports and 4.8 is required for Debian Jessie.
RUN rm -rf /usr/bin/gcc && ln -s /usr/bin/gcc-5 /usr/bin/gcc \
 && ln -s /usr/bin/gcc /usr/bin/gcc-4.9 \
 && ln -s /usr/bin/gcc /usr/bin/gcc-4.8

RUN rm -rf /usr/bin/clang \
 && rm -rf /usr/bin/llc \
 && ln -s /usr/bin/clang-7 /usr/bin/clang \
 && ln -s /usr/bin/llc-7 /usr/bin/llc

{% endif %}
{% if p.include_agent_package == "apt" %}
RUN curl -s https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public | apt-key add - \
 && curl -s -o /etc/apt/sources.list.d/draios.list http://download.draios.com/$SYSDIG_REPOSITORY/deb/draios.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends draios-agent \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

{% endif %}
{% if p.build_kernel_module %}
RUN rm -df /lib/modules \
 && ln -s $SYSDIG_HOST_ROOT/lib/modules /lib/modules

# debian:unstable head contains binutils 2.31, which generates
# binaries that are incompatible with kernels < 4.16. So manually
# forcibly install binutils 2.30-22 instead.
RUN curl -s -o binutils_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/binutils_2.30-22_amd64.deb \
 && curl -s -o libbinutils_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/libbinutils_2.30-22_amd64.deb \
 && curl -s -o binutils-x86-64-linux-gnu_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/binutils-x86-64-linux-gnu_2.30-22_amd64.deb \
 && curl -s -o binutils-common_2.30-22_amd64.deb https://s3.amazonaws.com/download.draios.com/dependencies/binutils-common_2.30-22_amd64.deb \
 && dpkg -i *binutils*.deb \
 && rm -f *binutils*.deb

{% endif %}
{% if p.include_agent_package == "local" %}
ADD draios-${AGENT_VERSION}-x86_64-agent.deb /
RUN dpkg -i /draios-${AGENT_VERSION}-x86_64-agent.deb

{% endif %}
COPY ./docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]

