// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics_list.proto

#include "metrics_list.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace draiosproto_w_metrics_list {
class metrics_listDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<metrics_list>
      _instance;
} _metrics_list_default_instance_;
}  // namespace draiosproto_w_metrics_list
namespace protobuf_metrics_5flist_2eproto {
void InitDefaultsmetrics_listImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_draios_2eproto::InitDefaultsmetrics();
  {
    void* ptr = &::draiosproto_w_metrics_list::_metrics_list_default_instance_;
    new (ptr) ::draiosproto_w_metrics_list::metrics_list();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::draiosproto_w_metrics_list::metrics_list::InitAsDefaultInstance();
}

void InitDefaultsmetrics_list() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsmetrics_listImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::draiosproto_w_metrics_list::metrics_list, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::draiosproto_w_metrics_list::metrics_list, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::draiosproto_w_metrics_list::metrics_list, metrics_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::draiosproto_w_metrics_list::metrics_list)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::draiosproto_w_metrics_list::_metrics_list_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "metrics_list.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022metrics_list.proto\022\032draiosproto_w_metr"
      "ics_list\032\014draios.proto\"5\n\014metrics_list\022%"
      "\n\007metrics\030\001 \003(\0132\024.draiosproto.metricsX\000"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 119);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "metrics_list.proto", &protobuf_RegisterTypes);
  ::protobuf_draios_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_metrics_5flist_2eproto
namespace draiosproto_w_metrics_list {

// ===================================================================

void metrics_list::InitAsDefaultInstance() {
}
void metrics_list::clear_metrics() {
  metrics_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int metrics_list::kMetricsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

metrics_list::metrics_list()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_metrics_5flist_2eproto::InitDefaultsmetrics_list();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:draiosproto_w_metrics_list.metrics_list)
}
metrics_list::metrics_list(const metrics_list& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      metrics_(from.metrics_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:draiosproto_w_metrics_list.metrics_list)
}

void metrics_list::SharedCtor() {
  _cached_size_ = 0;
}

metrics_list::~metrics_list() {
  // @@protoc_insertion_point(destructor:draiosproto_w_metrics_list.metrics_list)
  SharedDtor();
}

void metrics_list::SharedDtor() {
}

void metrics_list::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* metrics_list::descriptor() {
  ::protobuf_metrics_5flist_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_metrics_5flist_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const metrics_list& metrics_list::default_instance() {
  ::protobuf_metrics_5flist_2eproto::InitDefaultsmetrics_list();
  return *internal_default_instance();
}

metrics_list* metrics_list::New(::google::protobuf::Arena* arena) const {
  metrics_list* n = new metrics_list;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void metrics_list::Clear() {
// @@protoc_insertion_point(message_clear_start:draiosproto_w_metrics_list.metrics_list)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  metrics_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool metrics_list::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:draiosproto_w_metrics_list.metrics_list)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .draiosproto.metrics metrics = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_metrics()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:draiosproto_w_metrics_list.metrics_list)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:draiosproto_w_metrics_list.metrics_list)
  return false;
#undef DO_
}

void metrics_list::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:draiosproto_w_metrics_list.metrics_list)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .draiosproto.metrics metrics = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->metrics_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->metrics(static_cast<int>(i)), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:draiosproto_w_metrics_list.metrics_list)
}

::google::protobuf::uint8* metrics_list::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:draiosproto_w_metrics_list.metrics_list)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .draiosproto.metrics metrics = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->metrics_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->metrics(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:draiosproto_w_metrics_list.metrics_list)
  return target;
}

size_t metrics_list::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:draiosproto_w_metrics_list.metrics_list)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .draiosproto.metrics metrics = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->metrics_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->metrics(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void metrics_list::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:draiosproto_w_metrics_list.metrics_list)
  GOOGLE_DCHECK_NE(&from, this);
  const metrics_list* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const metrics_list>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:draiosproto_w_metrics_list.metrics_list)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:draiosproto_w_metrics_list.metrics_list)
    MergeFrom(*source);
  }
}

void metrics_list::MergeFrom(const metrics_list& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:draiosproto_w_metrics_list.metrics_list)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  metrics_.MergeFrom(from.metrics_);
}

void metrics_list::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:draiosproto_w_metrics_list.metrics_list)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void metrics_list::CopyFrom(const metrics_list& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:draiosproto_w_metrics_list.metrics_list)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool metrics_list::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->metrics())) return false;
  return true;
}

void metrics_list::Swap(metrics_list* other) {
  if (other == this) return;
  InternalSwap(other);
}
void metrics_list::InternalSwap(metrics_list* other) {
  using std::swap;
  metrics_.InternalSwap(&other->metrics_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata metrics_list::GetMetadata() const {
  protobuf_metrics_5flist_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_metrics_5flist_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace draiosproto_w_metrics_list

// @@protoc_insertion_point(global_scope)
