// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics_list.proto

#ifndef PROTOBUF_metrics_5flist_2eproto__INCLUDED
#define PROTOBUF_metrics_5flist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "draios.pb.h"
// @@protoc_insertion_point(includes)

namespace draiosproto_w_metrics_list {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_metrics_5flist_2eproto();
void protobuf_InitDefaults_metrics_5flist_2eproto();
void protobuf_AssignDesc_metrics_5flist_2eproto();
void protobuf_ShutdownFile_metrics_5flist_2eproto();

class metrics_list;

// ===================================================================

class metrics_list : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:draiosproto_w_metrics_list.metrics_list) */ {
 public:
  metrics_list();
  virtual ~metrics_list();

  metrics_list(const metrics_list& from);

  inline metrics_list& operator=(const metrics_list& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const metrics_list& default_instance();

  static const metrics_list* internal_default_instance();

  void Swap(metrics_list* other);

  // implements Message ----------------------------------------------

  inline metrics_list* New() const { return New(NULL); }

  metrics_list* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const metrics_list& from);
  void MergeFrom(const metrics_list& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(metrics_list* other);
  void UnsafeMergeFrom(const metrics_list& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .draiosproto.metrics metrics = 1;
  int metrics_size() const;
  void clear_metrics();
  static const int kMetricsFieldNumber = 1;
  const ::draiosproto::metrics& metrics(int index) const;
  ::draiosproto::metrics* mutable_metrics(int index);
  ::draiosproto::metrics* add_metrics();
  ::google::protobuf::RepeatedPtrField< ::draiosproto::metrics >*
      mutable_metrics();
  const ::google::protobuf::RepeatedPtrField< ::draiosproto::metrics >&
      metrics() const;

  // @@protoc_insertion_point(class_scope:draiosproto_w_metrics_list.metrics_list)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::draiosproto::metrics > metrics_;
  friend void  protobuf_InitDefaults_metrics_5flist_2eproto_impl();
  friend void  protobuf_AddDesc_metrics_5flist_2eproto_impl();
  friend void protobuf_AssignDesc_metrics_5flist_2eproto();
  friend void protobuf_ShutdownFile_metrics_5flist_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<metrics_list> metrics_list_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// metrics_list

// repeated .draiosproto.metrics metrics = 1;
inline int metrics_list::metrics_size() const {
  return metrics_.size();
}
inline void metrics_list::clear_metrics() {
  metrics_.Clear();
}
inline const ::draiosproto::metrics& metrics_list::metrics(int index) const {
  // @@protoc_insertion_point(field_get:draiosproto_w_metrics_list.metrics_list.metrics)
  return metrics_.Get(index);
}
inline ::draiosproto::metrics* metrics_list::mutable_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:draiosproto_w_metrics_list.metrics_list.metrics)
  return metrics_.Mutable(index);
}
inline ::draiosproto::metrics* metrics_list::add_metrics() {
  // @@protoc_insertion_point(field_add:draiosproto_w_metrics_list.metrics_list.metrics)
  return metrics_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::draiosproto::metrics >*
metrics_list::mutable_metrics() {
  // @@protoc_insertion_point(field_mutable_list:draiosproto_w_metrics_list.metrics_list.metrics)
  return &metrics_;
}
inline const ::google::protobuf::RepeatedPtrField< ::draiosproto::metrics >&
metrics_list::metrics() const {
  // @@protoc_insertion_point(field_list:draiosproto_w_metrics_list.metrics_list.metrics)
  return metrics_;
}

inline const metrics_list* metrics_list::internal_default_instance() {
  return &metrics_list_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace draiosproto_w_metrics_list

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_metrics_5flist_2eproto__INCLUDED
