// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdc_internal.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sdc_internal.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sdc_internal {

namespace {

const ::google::protobuf::Descriptor* container_mounts_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  container_mounts_reflection_ = NULL;
const ::google::protobuf::Descriptor* mounted_fs_response_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  mounted_fs_response_reflection_ = NULL;
const ::google::protobuf::Descriptor* container_info_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  container_info_reflection_ = NULL;
const ::google::protobuf::Descriptor* mounted_fs_request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  mounted_fs_request_reflection_ = NULL;
const ::google::protobuf::Descriptor* ping_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ping_reflection_ = NULL;
const ::google::protobuf::Descriptor* pong_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pong_reflection_ = NULL;
const ::google::protobuf::Descriptor* docker_command_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  docker_command_reflection_ = NULL;
const ::google::protobuf::Descriptor* docker_command_result_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  docker_command_result_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* cointerface_message_type_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* docker_cmd_type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_sdc_5finternal_2eproto() {
  protobuf_AddDesc_sdc_5finternal_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sdc_internal.proto");
  GOOGLE_CHECK(file != NULL);
  container_mounts_descriptor_ = file->message_type(0);
  static const int container_mounts_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_mounts, container_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_mounts, mounts_),
  };
  container_mounts_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      container_mounts_descriptor_,
      container_mounts::default_instance_,
      container_mounts_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_mounts, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_mounts, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(container_mounts));
  mounted_fs_response_descriptor_ = file->message_type(1);
  static const int mounted_fs_response_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mounted_fs_response, containers_),
  };
  mounted_fs_response_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      mounted_fs_response_descriptor_,
      mounted_fs_response::default_instance_,
      mounted_fs_response_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mounted_fs_response, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mounted_fs_response, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(mounted_fs_response));
  container_info_descriptor_ = file->message_type(2);
  static const int container_info_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_info, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_info, pid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_info, vpid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_info, root_),
  };
  container_info_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      container_info_descriptor_,
      container_info::default_instance_,
      container_info_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_info, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(container_info, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(container_info));
  mounted_fs_request_descriptor_ = file->message_type(3);
  static const int mounted_fs_request_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mounted_fs_request, containers_),
  };
  mounted_fs_request_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      mounted_fs_request_descriptor_,
      mounted_fs_request::default_instance_,
      mounted_fs_request_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mounted_fs_request, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mounted_fs_request, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(mounted_fs_request));
  ping_descriptor_ = file->message_type(4);
  static const int ping_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ping, token_),
  };
  ping_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ping_descriptor_,
      ping::default_instance_,
      ping_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ping, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ping, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ping));
  pong_descriptor_ = file->message_type(5);
  static const int pong_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pong, token_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pong, pid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pong, memory_used_),
  };
  pong_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      pong_descriptor_,
      pong::default_instance_,
      pong_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pong, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pong, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(pong));
  docker_command_descriptor_ = file->message_type(6);
  static const int docker_command_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command, cmd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command, container_id_),
  };
  docker_command_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      docker_command_descriptor_,
      docker_command::default_instance_,
      docker_command_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(docker_command));
  docker_command_result_descriptor_ = file->message_type(7);
  static const int docker_command_result_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command_result, successful_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command_result, errstr_),
  };
  docker_command_result_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      docker_command_result_descriptor_,
      docker_command_result::default_instance_,
      docker_command_result_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command_result, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(docker_command_result, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(docker_command_result));
  cointerface_message_type_descriptor_ = file->enum_type(0);
  docker_cmd_type_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sdc_5finternal_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    container_mounts_descriptor_, &container_mounts::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    mounted_fs_response_descriptor_, &mounted_fs_response::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    container_info_descriptor_, &container_info::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    mounted_fs_request_descriptor_, &mounted_fs_request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ping_descriptor_, &ping::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    pong_descriptor_, &pong::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    docker_command_descriptor_, &docker_command::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    docker_command_result_descriptor_, &docker_command_result::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sdc_5finternal_2eproto() {
  delete container_mounts::default_instance_;
  delete container_mounts_reflection_;
  delete mounted_fs_response::default_instance_;
  delete mounted_fs_response_reflection_;
  delete container_info::default_instance_;
  delete container_info_reflection_;
  delete mounted_fs_request::default_instance_;
  delete mounted_fs_request_reflection_;
  delete ping::default_instance_;
  delete ping_reflection_;
  delete pong::default_instance_;
  delete pong_reflection_;
  delete docker_command::default_instance_;
  delete docker_command_reflection_;
  delete docker_command_result::default_instance_;
  delete docker_command_result_reflection_;
}

void protobuf_AddDesc_sdc_5finternal_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::draiosproto::protobuf_AddDesc_draios_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022sdc_internal.proto\022\014sdc_internal\032\014drai"
    "os.proto\"Q\n\020container_mounts\022\024\n\014containe"
    "r_id\030\001 \002(\t\022\'\n\006mounts\030\002 \003(\0132\027.draiosproto"
    ".mounted_fs\"I\n\023mounted_fs_response\0222\n\nco"
    "ntainers\030\001 \003(\0132\036.sdc_internal.container_"
    "mounts\"E\n\016container_info\022\n\n\002id\030\001 \002(\t\022\013\n\003"
    "pid\030\002 \002(\004\022\014\n\004vpid\030\003 \002(\004\022\014\n\004root\030\004 \002(\t\"F\n"
    "\022mounted_fs_request\0220\n\ncontainers\030\001 \003(\0132"
    "\034.sdc_internal.container_info\"\025\n\004ping\022\r\n"
    "\005token\030\001 \002(\003\"7\n\004pong\022\r\n\005token\030\001 \002(\003\022\013\n\003p"
    "id\030\002 \002(\005\022\023\n\013memory_used\030\003 \002(\004\"R\n\016docker_"
    "command\022*\n\003cmd\030\001 \002(\0162\035.sdc_internal.dock"
    "er_cmd_type\022\024\n\014container_id\030\002 \001(\t\";\n\025doc"
    "ker_command_result\022\022\n\nsuccessful\030\001 \002(\010\022\016"
    "\n\006errstr\030\002 \001(\t*]\n\030cointerface_message_ty"
    "pe\022\010\n\004PING\020\001\022\010\n\004PONG\020\002\022\022\n\016DOCKER_COMMAND"
    "\020\003\022\031\n\025DOCKER_COMMAND_RESULT\020\004*3\n\017docker_"
    "cmd_type\022\010\n\004STOP\020\001\022\t\n\005PAUSE\020\002\022\013\n\007UNPAUSE"
    "\020\0032\243\001\n\013CoInterface\022[\n\024PerformDockerComma"
    "nd\022\034.sdc_internal.docker_command\032#.sdc_i"
    "nternal.docker_command_result\"\000\0227\n\013Perfo"
    "rmPing\022\022.sdc_internal.ping\032\022.sdc_interna"
    "l.pong\"\000B\002H\001", 892);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sdc_internal.proto", &protobuf_RegisterTypes);
  container_mounts::default_instance_ = new container_mounts();
  mounted_fs_response::default_instance_ = new mounted_fs_response();
  container_info::default_instance_ = new container_info();
  mounted_fs_request::default_instance_ = new mounted_fs_request();
  ping::default_instance_ = new ping();
  pong::default_instance_ = new pong();
  docker_command::default_instance_ = new docker_command();
  docker_command_result::default_instance_ = new docker_command_result();
  container_mounts::default_instance_->InitAsDefaultInstance();
  mounted_fs_response::default_instance_->InitAsDefaultInstance();
  container_info::default_instance_->InitAsDefaultInstance();
  mounted_fs_request::default_instance_->InitAsDefaultInstance();
  ping::default_instance_->InitAsDefaultInstance();
  pong::default_instance_->InitAsDefaultInstance();
  docker_command::default_instance_->InitAsDefaultInstance();
  docker_command_result::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sdc_5finternal_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sdc_5finternal_2eproto {
  StaticDescriptorInitializer_sdc_5finternal_2eproto() {
    protobuf_AddDesc_sdc_5finternal_2eproto();
  }
} static_descriptor_initializer_sdc_5finternal_2eproto_;
const ::google::protobuf::EnumDescriptor* cointerface_message_type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return cointerface_message_type_descriptor_;
}
bool cointerface_message_type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* docker_cmd_type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return docker_cmd_type_descriptor_;
}
bool docker_cmd_type_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int container_mounts::kContainerIdFieldNumber;
const int container_mounts::kMountsFieldNumber;
#endif  // !_MSC_VER

container_mounts::container_mounts()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void container_mounts::InitAsDefaultInstance() {
}

container_mounts::container_mounts(const container_mounts& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void container_mounts::SharedCtor() {
  _cached_size_ = 0;
  container_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

container_mounts::~container_mounts() {
  SharedDtor();
}

void container_mounts::SharedDtor() {
  if (container_id_ != &::google::protobuf::internal::kEmptyString) {
    delete container_id_;
  }
  if (this != default_instance_) {
  }
}

void container_mounts::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* container_mounts::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return container_mounts_descriptor_;
}

const container_mounts& container_mounts::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

container_mounts* container_mounts::default_instance_ = NULL;

container_mounts* container_mounts::New() const {
  return new container_mounts;
}

void container_mounts::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_container_id()) {
      if (container_id_ != &::google::protobuf::internal::kEmptyString) {
        container_id_->clear();
      }
    }
  }
  mounts_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool container_mounts::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string container_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_container_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->container_id().data(), this->container_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_mounts;
        break;
      }

      // repeated .draiosproto.mounted_fs mounts = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_mounts:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_mounts()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_mounts;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void container_mounts::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string container_id = 1;
  if (has_container_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->container_id().data(), this->container_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->container_id(), output);
  }

  // repeated .draiosproto.mounted_fs mounts = 2;
  for (int i = 0; i < this->mounts_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->mounts(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* container_mounts::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string container_id = 1;
  if (has_container_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->container_id().data(), this->container_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->container_id(), target);
  }

  // repeated .draiosproto.mounted_fs mounts = 2;
  for (int i = 0; i < this->mounts_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->mounts(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int container_mounts::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string container_id = 1;
    if (has_container_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->container_id());
    }

  }
  // repeated .draiosproto.mounted_fs mounts = 2;
  total_size += 1 * this->mounts_size();
  for (int i = 0; i < this->mounts_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->mounts(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void container_mounts::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const container_mounts* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const container_mounts*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void container_mounts::MergeFrom(const container_mounts& from) {
  GOOGLE_CHECK_NE(&from, this);
  mounts_.MergeFrom(from.mounts_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_container_id()) {
      set_container_id(from.container_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void container_mounts::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void container_mounts::CopyFrom(const container_mounts& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool container_mounts::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < mounts_size(); i++) {
    if (!this->mounts(i).IsInitialized()) return false;
  }
  return true;
}

void container_mounts::Swap(container_mounts* other) {
  if (other != this) {
    std::swap(container_id_, other->container_id_);
    mounts_.Swap(&other->mounts_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata container_mounts::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = container_mounts_descriptor_;
  metadata.reflection = container_mounts_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int mounted_fs_response::kContainersFieldNumber;
#endif  // !_MSC_VER

mounted_fs_response::mounted_fs_response()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void mounted_fs_response::InitAsDefaultInstance() {
}

mounted_fs_response::mounted_fs_response(const mounted_fs_response& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void mounted_fs_response::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

mounted_fs_response::~mounted_fs_response() {
  SharedDtor();
}

void mounted_fs_response::SharedDtor() {
  if (this != default_instance_) {
  }
}

void mounted_fs_response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* mounted_fs_response::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return mounted_fs_response_descriptor_;
}

const mounted_fs_response& mounted_fs_response::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

mounted_fs_response* mounted_fs_response::default_instance_ = NULL;

mounted_fs_response* mounted_fs_response::New() const {
  return new mounted_fs_response;
}

void mounted_fs_response::Clear() {
  containers_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool mounted_fs_response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .sdc_internal.container_mounts containers = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_containers:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_containers()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_containers;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void mounted_fs_response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .sdc_internal.container_mounts containers = 1;
  for (int i = 0; i < this->containers_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->containers(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* mounted_fs_response::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .sdc_internal.container_mounts containers = 1;
  for (int i = 0; i < this->containers_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->containers(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int mounted_fs_response::ByteSize() const {
  int total_size = 0;

  // repeated .sdc_internal.container_mounts containers = 1;
  total_size += 1 * this->containers_size();
  for (int i = 0; i < this->containers_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->containers(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void mounted_fs_response::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const mounted_fs_response* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const mounted_fs_response*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void mounted_fs_response::MergeFrom(const mounted_fs_response& from) {
  GOOGLE_CHECK_NE(&from, this);
  containers_.MergeFrom(from.containers_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void mounted_fs_response::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mounted_fs_response::CopyFrom(const mounted_fs_response& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mounted_fs_response::IsInitialized() const {

  for (int i = 0; i < containers_size(); i++) {
    if (!this->containers(i).IsInitialized()) return false;
  }
  return true;
}

void mounted_fs_response::Swap(mounted_fs_response* other) {
  if (other != this) {
    containers_.Swap(&other->containers_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata mounted_fs_response::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = mounted_fs_response_descriptor_;
  metadata.reflection = mounted_fs_response_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int container_info::kIdFieldNumber;
const int container_info::kPidFieldNumber;
const int container_info::kVpidFieldNumber;
const int container_info::kRootFieldNumber;
#endif  // !_MSC_VER

container_info::container_info()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void container_info::InitAsDefaultInstance() {
}

container_info::container_info(const container_info& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void container_info::SharedCtor() {
  _cached_size_ = 0;
  id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  pid_ = GOOGLE_ULONGLONG(0);
  vpid_ = GOOGLE_ULONGLONG(0);
  root_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

container_info::~container_info() {
  SharedDtor();
}

void container_info::SharedDtor() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    delete id_;
  }
  if (root_ != &::google::protobuf::internal::kEmptyString) {
    delete root_;
  }
  if (this != default_instance_) {
  }
}

void container_info::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* container_info::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return container_info_descriptor_;
}

const container_info& container_info::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

container_info* container_info::default_instance_ = NULL;

container_info* container_info::New() const {
  return new container_info;
}

void container_info::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_id()) {
      if (id_ != &::google::protobuf::internal::kEmptyString) {
        id_->clear();
      }
    }
    pid_ = GOOGLE_ULONGLONG(0);
    vpid_ = GOOGLE_ULONGLONG(0);
    if (has_root()) {
      if (root_ != &::google::protobuf::internal::kEmptyString) {
        root_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool container_info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_pid;
        break;
      }

      // required uint64 pid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_pid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &pid_)));
          set_has_pid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_vpid;
        break;
      }

      // required uint64 vpid = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vpid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &vpid_)));
          set_has_vpid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_root;
        break;
      }

      // required string root = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_root:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_root()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->root().data(), this->root().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void container_info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->id(), output);
  }

  // required uint64 pid = 2;
  if (has_pid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->pid(), output);
  }

  // required uint64 vpid = 3;
  if (has_vpid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->vpid(), output);
  }

  // required string root = 4;
  if (has_root()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->root().data(), this->root().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->root(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* container_info::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  // required uint64 pid = 2;
  if (has_pid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->pid(), target);
  }

  // required uint64 vpid = 3;
  if (has_vpid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->vpid(), target);
  }

  // required string root = 4;
  if (has_root()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->root().data(), this->root().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->root(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int container_info::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->id());
    }

    // required uint64 pid = 2;
    if (has_pid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->pid());
    }

    // required uint64 vpid = 3;
    if (has_vpid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->vpid());
    }

    // required string root = 4;
    if (has_root()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->root());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void container_info::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const container_info* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const container_info*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void container_info::MergeFrom(const container_info& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_pid()) {
      set_pid(from.pid());
    }
    if (from.has_vpid()) {
      set_vpid(from.vpid());
    }
    if (from.has_root()) {
      set_root(from.root());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void container_info::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void container_info::CopyFrom(const container_info& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool container_info::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void container_info::Swap(container_info* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(pid_, other->pid_);
    std::swap(vpid_, other->vpid_);
    std::swap(root_, other->root_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata container_info::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = container_info_descriptor_;
  metadata.reflection = container_info_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int mounted_fs_request::kContainersFieldNumber;
#endif  // !_MSC_VER

mounted_fs_request::mounted_fs_request()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void mounted_fs_request::InitAsDefaultInstance() {
}

mounted_fs_request::mounted_fs_request(const mounted_fs_request& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void mounted_fs_request::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

mounted_fs_request::~mounted_fs_request() {
  SharedDtor();
}

void mounted_fs_request::SharedDtor() {
  if (this != default_instance_) {
  }
}

void mounted_fs_request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* mounted_fs_request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return mounted_fs_request_descriptor_;
}

const mounted_fs_request& mounted_fs_request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

mounted_fs_request* mounted_fs_request::default_instance_ = NULL;

mounted_fs_request* mounted_fs_request::New() const {
  return new mounted_fs_request;
}

void mounted_fs_request::Clear() {
  containers_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool mounted_fs_request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .sdc_internal.container_info containers = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_containers:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_containers()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_containers;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void mounted_fs_request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .sdc_internal.container_info containers = 1;
  for (int i = 0; i < this->containers_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->containers(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* mounted_fs_request::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .sdc_internal.container_info containers = 1;
  for (int i = 0; i < this->containers_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->containers(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int mounted_fs_request::ByteSize() const {
  int total_size = 0;

  // repeated .sdc_internal.container_info containers = 1;
  total_size += 1 * this->containers_size();
  for (int i = 0; i < this->containers_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->containers(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void mounted_fs_request::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const mounted_fs_request* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const mounted_fs_request*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void mounted_fs_request::MergeFrom(const mounted_fs_request& from) {
  GOOGLE_CHECK_NE(&from, this);
  containers_.MergeFrom(from.containers_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void mounted_fs_request::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mounted_fs_request::CopyFrom(const mounted_fs_request& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mounted_fs_request::IsInitialized() const {

  for (int i = 0; i < containers_size(); i++) {
    if (!this->containers(i).IsInitialized()) return false;
  }
  return true;
}

void mounted_fs_request::Swap(mounted_fs_request* other) {
  if (other != this) {
    containers_.Swap(&other->containers_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata mounted_fs_request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = mounted_fs_request_descriptor_;
  metadata.reflection = mounted_fs_request_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ping::kTokenFieldNumber;
#endif  // !_MSC_VER

ping::ping()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ping::InitAsDefaultInstance() {
}

ping::ping(const ping& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ping::SharedCtor() {
  _cached_size_ = 0;
  token_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ping::~ping() {
  SharedDtor();
}

void ping::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ping::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ping::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ping_descriptor_;
}

const ping& ping::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

ping* ping::default_instance_ = NULL;

ping* ping::New() const {
  return new ping;
}

void ping::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    token_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ping::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 token = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &token_)));
          set_has_token();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ping::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 token = 1;
  if (has_token()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->token(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ping::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 token = 1;
  if (has_token()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->token(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ping::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 token = 1;
    if (has_token()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->token());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ping::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ping* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ping*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ping::MergeFrom(const ping& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_token()) {
      set_token(from.token());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ping::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ping::CopyFrom(const ping& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ping::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ping::Swap(ping* other) {
  if (other != this) {
    std::swap(token_, other->token_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ping::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ping_descriptor_;
  metadata.reflection = ping_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int pong::kTokenFieldNumber;
const int pong::kPidFieldNumber;
const int pong::kMemoryUsedFieldNumber;
#endif  // !_MSC_VER

pong::pong()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void pong::InitAsDefaultInstance() {
}

pong::pong(const pong& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void pong::SharedCtor() {
  _cached_size_ = 0;
  token_ = GOOGLE_LONGLONG(0);
  pid_ = 0;
  memory_used_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

pong::~pong() {
  SharedDtor();
}

void pong::SharedDtor() {
  if (this != default_instance_) {
  }
}

void pong::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pong::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pong_descriptor_;
}

const pong& pong::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

pong* pong::default_instance_ = NULL;

pong* pong::New() const {
  return new pong;
}

void pong::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    token_ = GOOGLE_LONGLONG(0);
    pid_ = 0;
    memory_used_ = GOOGLE_ULONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool pong::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 token = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &token_)));
          set_has_token();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_pid;
        break;
      }

      // required int32 pid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_pid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pid_)));
          set_has_pid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_memory_used;
        break;
      }

      // required uint64 memory_used = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_memory_used:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &memory_used_)));
          set_has_memory_used();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void pong::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 token = 1;
  if (has_token()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->token(), output);
  }

  // required int32 pid = 2;
  if (has_pid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->pid(), output);
  }

  // required uint64 memory_used = 3;
  if (has_memory_used()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->memory_used(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* pong::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 token = 1;
  if (has_token()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->token(), target);
  }

  // required int32 pid = 2;
  if (has_pid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->pid(), target);
  }

  // required uint64 memory_used = 3;
  if (has_memory_used()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->memory_used(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int pong::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 token = 1;
    if (has_token()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->token());
    }

    // required int32 pid = 2;
    if (has_pid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->pid());
    }

    // required uint64 memory_used = 3;
    if (has_memory_used()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->memory_used());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pong::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const pong* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const pong*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void pong::MergeFrom(const pong& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_token()) {
      set_token(from.token());
    }
    if (from.has_pid()) {
      set_pid(from.pid());
    }
    if (from.has_memory_used()) {
      set_memory_used(from.memory_used());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void pong::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pong::CopyFrom(const pong& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pong::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void pong::Swap(pong* other) {
  if (other != this) {
    std::swap(token_, other->token_);
    std::swap(pid_, other->pid_);
    std::swap(memory_used_, other->memory_used_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata pong::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pong_descriptor_;
  metadata.reflection = pong_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int docker_command::kCmdFieldNumber;
const int docker_command::kContainerIdFieldNumber;
#endif  // !_MSC_VER

docker_command::docker_command()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void docker_command::InitAsDefaultInstance() {
}

docker_command::docker_command(const docker_command& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void docker_command::SharedCtor() {
  _cached_size_ = 0;
  cmd_ = 1;
  container_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

docker_command::~docker_command() {
  SharedDtor();
}

void docker_command::SharedDtor() {
  if (container_id_ != &::google::protobuf::internal::kEmptyString) {
    delete container_id_;
  }
  if (this != default_instance_) {
  }
}

void docker_command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* docker_command::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return docker_command_descriptor_;
}

const docker_command& docker_command::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

docker_command* docker_command::default_instance_ = NULL;

docker_command* docker_command::New() const {
  return new docker_command;
}

void docker_command::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    cmd_ = 1;
    if (has_container_id()) {
      if (container_id_ != &::google::protobuf::internal::kEmptyString) {
        container_id_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool docker_command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .sdc_internal.docker_cmd_type cmd = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sdc_internal::docker_cmd_type_IsValid(value)) {
            set_cmd(static_cast< ::sdc_internal::docker_cmd_type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_container_id;
        break;
      }

      // optional string container_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_container_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_container_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->container_id().data(), this->container_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void docker_command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .sdc_internal.docker_cmd_type cmd = 1;
  if (has_cmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->cmd(), output);
  }

  // optional string container_id = 2;
  if (has_container_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->container_id().data(), this->container_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->container_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* docker_command::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .sdc_internal.docker_cmd_type cmd = 1;
  if (has_cmd()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->cmd(), target);
  }

  // optional string container_id = 2;
  if (has_container_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->container_id().data(), this->container_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->container_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int docker_command::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .sdc_internal.docker_cmd_type cmd = 1;
    if (has_cmd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->cmd());
    }

    // optional string container_id = 2;
    if (has_container_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->container_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void docker_command::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const docker_command* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const docker_command*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void docker_command::MergeFrom(const docker_command& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cmd()) {
      set_cmd(from.cmd());
    }
    if (from.has_container_id()) {
      set_container_id(from.container_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void docker_command::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void docker_command::CopyFrom(const docker_command& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool docker_command::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void docker_command::Swap(docker_command* other) {
  if (other != this) {
    std::swap(cmd_, other->cmd_);
    std::swap(container_id_, other->container_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata docker_command::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = docker_command_descriptor_;
  metadata.reflection = docker_command_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int docker_command_result::kSuccessfulFieldNumber;
const int docker_command_result::kErrstrFieldNumber;
#endif  // !_MSC_VER

docker_command_result::docker_command_result()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void docker_command_result::InitAsDefaultInstance() {
}

docker_command_result::docker_command_result(const docker_command_result& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void docker_command_result::SharedCtor() {
  _cached_size_ = 0;
  successful_ = false;
  errstr_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

docker_command_result::~docker_command_result() {
  SharedDtor();
}

void docker_command_result::SharedDtor() {
  if (errstr_ != &::google::protobuf::internal::kEmptyString) {
    delete errstr_;
  }
  if (this != default_instance_) {
  }
}

void docker_command_result::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* docker_command_result::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return docker_command_result_descriptor_;
}

const docker_command_result& docker_command_result::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sdc_5finternal_2eproto();
  return *default_instance_;
}

docker_command_result* docker_command_result::default_instance_ = NULL;

docker_command_result* docker_command_result::New() const {
  return new docker_command_result;
}

void docker_command_result::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    successful_ = false;
    if (has_errstr()) {
      if (errstr_ != &::google::protobuf::internal::kEmptyString) {
        errstr_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool docker_command_result::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool successful = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &successful_)));
          set_has_successful();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_errstr;
        break;
      }

      // optional string errstr = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_errstr:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_errstr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->errstr().data(), this->errstr().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void docker_command_result::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool successful = 1;
  if (has_successful()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->successful(), output);
  }

  // optional string errstr = 2;
  if (has_errstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->errstr().data(), this->errstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->errstr(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* docker_command_result::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool successful = 1;
  if (has_successful()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->successful(), target);
  }

  // optional string errstr = 2;
  if (has_errstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->errstr().data(), this->errstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->errstr(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int docker_command_result::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool successful = 1;
    if (has_successful()) {
      total_size += 1 + 1;
    }

    // optional string errstr = 2;
    if (has_errstr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->errstr());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void docker_command_result::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const docker_command_result* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const docker_command_result*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void docker_command_result::MergeFrom(const docker_command_result& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_successful()) {
      set_successful(from.successful());
    }
    if (from.has_errstr()) {
      set_errstr(from.errstr());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void docker_command_result::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void docker_command_result::CopyFrom(const docker_command_result& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool docker_command_result::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void docker_command_result::Swap(docker_command_result* other) {
  if (other != this) {
    std::swap(successful_, other->successful_);
    std::swap(errstr_, other->errstr_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata docker_command_result::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = docker_command_result_descriptor_;
  metadata.reflection = docker_command_result_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sdc_internal

// @@protoc_insertion_point(global_scope)
