# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='draiosproto',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x0b\x64raiosproto\"L\n\x13\x61ggregations_double\x12\x0e\n\x06weight\x18\x01 \x02(\x04\x12\x0b\n\x03max\x18\x02 \x02(\x01\x12\x0b\n\x03min\x18\x03 \x02(\x01\x12\x0b\n\x03sum\x18\x04 \x02(\x01\"g\n\x11\x61pp_metric_bucket\x12\r\n\x05label\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\x12\x34\n\naggr_count\x18\x03 \x01(\x0b\x32 .draiosproto.aggregations_double\"\x7f\n\x17\x63ounter_percentile_data\x12\r\n\x05scale\x18\x01 \x02(\r\x12\x13\n\x0bnum_samples\x18\x02 \x02(\r\x12\x0b\n\x03min\x18\x03 \x02(\x04\x12\x0b\n\x03max\x18\x04 \x02(\x04\x12\x11\n\x05means\x18\x05 \x03(\x04\x42\x02\x10\x01\x12\x13\n\x07weights\x18\x06 \x03(\rB\x02\x10\x01\x42-\n\x19\x63om.draios.model.protobufB\x0eProtobufCommonH\x01')
)




_AGGREGATIONS_DOUBLE = _descriptor.Descriptor(
  name='aggregations_double',
  full_name='draiosproto.aggregations_double',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='draiosproto.aggregations_double.weight', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='draiosproto.aggregations_double.max', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='draiosproto.aggregations_double.min', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sum', full_name='draiosproto.aggregations_double.sum', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=105,
)


_APP_METRIC_BUCKET = _descriptor.Descriptor(
  name='app_metric_bucket',
  full_name='draiosproto.app_metric_bucket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='draiosproto.app_metric_bucket.label', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='draiosproto.app_metric_bucket.count', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggr_count', full_name='draiosproto.app_metric_bucket.aggr_count', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=210,
)


_COUNTER_PERCENTILE_DATA = _descriptor.Descriptor(
  name='counter_percentile_data',
  full_name='draiosproto.counter_percentile_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scale', full_name='draiosproto.counter_percentile_data.scale', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_samples', full_name='draiosproto.counter_percentile_data.num_samples', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='draiosproto.counter_percentile_data.min', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='draiosproto.counter_percentile_data.max', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='means', full_name='draiosproto.counter_percentile_data.means', index=4,
      number=5, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='draiosproto.counter_percentile_data.weights', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=339,
)

_APP_METRIC_BUCKET.fields_by_name['aggr_count'].message_type = _AGGREGATIONS_DOUBLE
DESCRIPTOR.message_types_by_name['aggregations_double'] = _AGGREGATIONS_DOUBLE
DESCRIPTOR.message_types_by_name['app_metric_bucket'] = _APP_METRIC_BUCKET
DESCRIPTOR.message_types_by_name['counter_percentile_data'] = _COUNTER_PERCENTILE_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

aggregations_double = _reflection.GeneratedProtocolMessageType('aggregations_double', (_message.Message,), dict(
  DESCRIPTOR = _AGGREGATIONS_DOUBLE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:draiosproto.aggregations_double)
  ))
_sym_db.RegisterMessage(aggregations_double)

app_metric_bucket = _reflection.GeneratedProtocolMessageType('app_metric_bucket', (_message.Message,), dict(
  DESCRIPTOR = _APP_METRIC_BUCKET,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:draiosproto.app_metric_bucket)
  ))
_sym_db.RegisterMessage(app_metric_bucket)

counter_percentile_data = _reflection.GeneratedProtocolMessageType('counter_percentile_data', (_message.Message,), dict(
  DESCRIPTOR = _COUNTER_PERCENTILE_DATA,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:draiosproto.counter_percentile_data)
  ))
_sym_db.RegisterMessage(counter_percentile_data)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.draios.model.protobufB\016ProtobufCommonH\001'))
_COUNTER_PERCENTILE_DATA.fields_by_name['means'].has_options = True
_COUNTER_PERCENTILE_DATA.fields_by_name['means']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_COUNTER_PERCENTILE_DATA.fields_by_name['weights'].has_options = True
_COUNTER_PERCENTILE_DATA.fields_by_name['weights']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
