#!/bin/bash
set -exu

SCRIPT=$(readlink -f $0)
TOP=$(dirname $SCRIPT)

RELEASE_TYPE=$1

cd $TOP/../..
agent/setup-dependencies
make -C agent/build/debug package
make -C agent/build/release package
make -C sysdig/build/debug package
make -C sysdig/build/release package

rm -rf /tmp/packages
mkdir -p /tmp/packages/debug
mkdir -p /tmp/packages/release

case "$RELEASE_TYPE" in
	internal)
		cp {agent,sysdig}/build/debug/*{deb,rpm} /tmp/packages/debug
		cp {agent,sysdig}/build/release/*{deb,rpm} /tmp/packages/release
		;;
	public)
		cp {agent,sysdig}/build/debug/*{deb,rpm} /tmp/packages/debug
		cp agent/build/release/*agent*{deb,rpm} /tmp/packages/release # copy agent and not tests
		cp sysdig/build/release/*{deb,rpm} /tmp/packages/release
		;;
	*) 
		false
		;;
esac
