#!/bin/bash
set -exu

./setup-dependencies
make -C build/debug package
make -C build/release package

rm -rf /tmp/packages
mkdir /tmp/packages
cp build/debug/*rpm /tmp/packages
cp build/release/*rpm /tmp/packages
cp build/debug/*deb /tmp/packages
cp build/release/*deb /tmp/packages
