#!/bin/bash
set -exu

SCRIPT=$(readlink -f $0)
TOP=$(dirname $SCRIPT)

RELEASE_TYPE=$1

cd $TOP/..
./setup-dependencies
# make -C build/debug package
make -C build/release package

cd $TOP/../../sysdig
./bootstrap
# make -C build/debug package
make -C build/release package

rm -rf /tmp/packages
mkdir /tmp/packages

case "$RELEASE_TYPE" in
	internal)
		# cp $TOP/../build/{debug,release}/*{deb,rpm} /tmp/packages
		# cp $TOP/../../sysdig/build/{debug,release}/*{deb,rpm} /tmp/packages
		cp $TOP/../build/release/*{deb,rpm} /tmp/packages
		cp $TOP/../../sysdig/build/release/*{deb,rpm} /tmp/packages
		;;
	public)
		cp $TOP/../build/release/*agent*{deb,rpm} /tmp/packages
		cp $TOP/../../sysdig/build/release/*{deb,rpm} /tmp/packages
		;;
	*) 
		false
		;;
esac
