#!/bin/bash
set -exu

SYSDIG_VERSION=$1
REPOSITORY_NAME=$2
BASEDIR=$(pwd)
ARCH=$(uname -m)

function coreos_build {
	KERNEL_RELEASE=$1
	KERNEL_CONFIG=$2

	if [ ! -f linux-$KERNEL_RELEASE.tar.xz ]; then
		wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-$KERNEL_RELEASE.tar.xz
	fi

	if [ ! -d linux-$KERNEL_RELEASE ]; then
		tar xf linux-$KERNEL_RELEASE.tar.xz
		cd linux-$KERNEL_RELEASE
		make distclean
		wget -O .config $KERNEL_CONFIG
		sed -i s/"CONFIG_BLK_DEV_INITRD=y"/"# CONFIG_BLK_DEV_INITRD is not set"/ .config
		make -j8 all
		cd $BASEDIR
	fi

	if [ ! -f $SYSDIG_VERSION.tar.gz ]; then
		wget https://github.com/draios/sysdig/archive/$SYSDIG_VERSION.tar.gz
	fi

	wget -O config $KERNEL_CONFIG
	HASH1=$(md5sum config | cut -d' ' -f1)
	sed -i s/"# Linux\/x86"/"# Linux\/x86_64"/ config
	HASH2=$(md5sum config | cut -d' ' -f1)
	rm -rf config

	rm -rf sysdig-$SYSDIG_VERSION
	tar zxf $SYSDIG_VERSION.tar.gz
	cd sysdig-$SYSDIG_VERSION
	mkdir build
	cd build
	cmake -DCMAKE_BUILD_TYPE=Release -DSYSDIG_VERSION=$SYSDIG_VERSION ..
	KERNELDIR=$BASEDIR/linux-$KERNEL_RELEASE make driver
	strip -g driver/sysdig-probe.ko
	cp driver/sysdig-probe.ko $BASEDIR/sysdig-probe-$SYSDIG_VERSION-$ARCH-$KERNEL_RELEASE-$HASH1.ko
	cp driver/sysdig-probe.ko $BASEDIR/sysdig-probe-$SYSDIG_VERSION-$ARCH-$KERNEL_RELEASE-$HASH2.ko
	cd $BASEDIR
}

coreos_build 3.18.1 https://raw.githubusercontent.com/coreos/coreos-overlay/master/sys-kernel/coreos-kernel/files/amd64_defconfig-3.18
coreos_build 3.17.7 https://raw.githubusercontent.com/coreos/coreos-overlay/build-522/sys-kernel/coreos-kernel/files/x86_64_defconfig-3.17.7
coreos_build 3.17.2 https://raw.githubusercontent.com/coreos/coreos-overlay/build-494/sys-kernel/coreos-kernel/files/x86_64_defconfig-3.17.2

aws s3 cp . s3://download.draios.com/$REPOSITORY_NAME/sysdig-probe-binaries/ --recursive --exclude "*" --include "sysdig-probe*.ko" --acl public-read
