#!/bin/bash
set -exu

SYSDIG_VERSION=$1
REPOSITORY_NAME=$2
BASEDIR=$(pwd)
ARCH=$(uname -m)

function coreos_build {
	KERNEL_RELEASE=$1
	KERNEL_CONFIG=$2

	if [ ! -f linux-$KERNEL_RELEASE.tar.xz ]; then
		wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-$KERNEL_RELEASE.tar.xz
	fi

	if [ ! -d linux-$KERNEL_RELEASE ]; then
		tar xf linux-$KERNEL_RELEASE.tar.xz
		cd linux-$KERNEL_RELEASE
		make distclean
		wget -O .config $KERNEL_CONFIG
		sed -i s/"CONFIG_BLK_DEV_INITRD=y"/"# CONFIG_BLK_DEV_INITRD is not set"/ .config
		make -j8 all
		cd $BASEDIR
	fi

	if [ ! -f $SYSDIG_VERSION.tar.gz ]; then
		wget https://github.com/draios/sysdig/archive/$SYSDIG_VERSION.tar.gz
	fi

	wget -O config $KERNEL_CONFIG
	HASH=$(md5sum config | cut -d' ' -f1)
	rm -rf config

	rm -rf sysdig-$SYSDIG_VERSION
	tar zxf $SYSDIG_VERSION.tar.gz
	cd sysdig-$SYSDIG_VERSION
	mkdir build
	cd build
	cmake -DCMAKE_BUILD_TYPE=Release -DSYSDIG_VERSION=$SYSDIG_VERSION ..
	KERNELDIR=$BASEDIR/linux-$KERNEL_RELEASE make driver
	strip -g driver/sysdig-probe.ko
	cp driver/sysdig-probe.ko $BASEDIR/sysdig-probe-$SYSDIG_VERSION-$ARCH-$KERNEL_RELEASE-$HASH.ko
	cd $BASEDIR
}

coreos_build 3.18.1 https://raw.githubusercontent.com/coreos/coreos-overlay/463d19f583961ddf9cc89f26350af2a828a1fa82/sys-kernel/coreos-kernel/files/amd64_defconfig-3.18
coreos_build 3.18.4 https://raw.githubusercontent.com/coreos/coreos-overlay/bee2fa74623b87beede7f9397cb7278e9d409049/sys-kernel/coreos-kernel/files/amd64_defconfig-3.18
coreos_build 3.18.6 https://raw.githubusercontent.com/coreos/coreos-overlay/b38dabe01e756f7265983d126f33b947a693091d/sys-kernel/coreos-kernel/files/amd64_defconfig-3.18

aws s3 cp . s3://download.draios.com/$REPOSITORY_NAME/sysdig-probe-binaries/ --recursive --exclude "*" --include "sysdig-probe*.ko" --acl public-read
