#!/bin/bash
set -exu

SYSDIG_RELEASE=$1
SYSDIG_REPOSITORY=$2
BASEDIR=$(pwd)

function coreos_build {
	KERNEL_RELEASE=$1
	KERNEL_CONFIG=$2

	if [ ! -f linux-$KERNEL_RELEASE.tar.xz ]; then
		wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-$KERNEL_RELEASE.tar.xz
	fi

	if [ ! -d linux-$KERNEL_RELEASE ]; then
		tar xf linux-$KERNEL_RELEASE.tar.xz
		cd linux-$KERNEL_RELEASE
		make distclean
		wget -O .config $KERNEL_CONFIG
		sed -i s/"CONFIG_BLK_DEV_INITRD=y"/"# CONFIG_BLK_DEV_INITRD is not set"/ .config
		make -j8 all
		cd $BASEDIR
	fi

	if [ ! -f $SYSDIG_RELEASE.tar.gz ]; then
		wget https://github.com/draios/sysdig/archive/$SYSDIG_RELEASE.tar.gz
	fi

	rm -rf sysdig-$SYSDIG_RELEASE
	tar zxf $SYSDIG_RELEASE.tar.gz
	cd sysdig-$SYSDIG_RELEASE
	mkdir build
	cd build
	cmake -DCMAKE_BUILD_TYPE=Release ..
	KERNELDIR=$BASEDIR/linux-$KERNEL_RELEASE make driver
	strip -g driver/sysdig-probe.ko
	cp driver/sysdig-probe.ko $BASEDIR/sysdig-probe-$SYSDIG_RELEASE-$KERNEL_RELEASE.ko
	cd $BASEDIR
}

coreos_build 3.17.7 https://raw.githubusercontent.com/coreos/coreos-overlay/build-522/sys-kernel/coreos-kernel/files/x86_64_defconfig-3.17.7
coreos_build 3.17.2 https://raw.githubusercontent.com/coreos/coreos-overlay/build-494/sys-kernel/coreos-kernel/files/x86_64_defconfig-3.17.2
