#!/bin/bash
set -exu

REPOSITORY_NAME="$1"

function smoke_tests {
	service dragent start
	sleep 2
	test -e /var/run/dragent.pid
	service dragent status
	MONITOR_PID=$(cat /var/run/dragent.pid)
	AGENT_PID=$(pidof -o $MONITOR_PID dragent)
	kill -SIGKILL $AGENT_PID
	sleep 2
	pidof -o $MONITOR_PID dragent
	service dragent restart
	sleep 2
	MONITOR_PID=$(cat /var/run/dragent.pid)
	pidof -o $MONITOR_PID dragent
	service dragent stop
	test ! -e /var/run/dragent.pid
	service dragent status && false
	pidof dragent && false

	modprobe ppm
	sh -c "cd /opt/draios/test; ./test"
	rmmod ppm
}

function install_rpm {
	yum -y erase draios-agent draios-tests draios-debug-agent draios-debug-tests

	if ! yum info dkms; then
		rpm -i http://mirror.us.leaseweb.net/epel/6/i386/epel-release-6-8.noarch.rpm # needed for dkms
	fi

	curl -o /etc/yum.repos.d/draios.repo http://download.draios.com/$REPOSITORY_NAME/rpm/draios.repo
	yum -y install kernel-devel-$(uname -r) # this is needed if the customer doesn't have the most updated kernel version
	yum -y install draios-agent draios-tests
}

function install_deb {
	apt-get -y purge draios-agent draios-tests draios-debug-agent draios-debug-tests || true
	
	curl -o /etc/apt/sources.list.d/draios.list http://download.draios.com/$REPOSITORY_NAME/deb/draios.list
	apt-get update
	apt-get -y install linux-headers-$(uname -r) # this is needed if the customer doesn't have the most updated kernel version
	apt-get -y --force-yes install draios-agent draios-tests
}

function install_debug_rpm {
	yum -y erase draios-agent draios-tests draios-debug-agent draios-debug-tests
	yum -y install draios-debug-agent draios-debug-tests
}

function install_debug_deb {
	apt-get -y purge draios-agent draios-tests draios-debug-agent draios-debug-tests || true
	apt-get -y --force-yes install draios-debug-agent draios-debug-tests
}

if [ -f /etc/debian_version ]; then
    install_deb
elif [ -f /etc/redhat-release ]; then
    install_rpm
else
    echo "Unable to detect operating system."
    exit 1
fi

smoke_tests

if [ -f /etc/debian_version ]; then
    install_debug_deb
elif [ -f /etc/redhat-release ]; then
    install_debug_rpm
else
    echo "Unable to detect operating system."
    exit 1
fi

smoke_tests
