#!/bin/bash
# Tool to collect log files for Sysdig Cloud Agent
# www.sysdig.com
#
# (c) 2017 Sysdig Inc.
#


HOME_DIR="/opt/draios"
HOME_DIR_S=${HOME_DIR:1}
LOG_DIR="$HOME_DIR/logs"
ETC_DIR="$HOME_DIR/etc"
CUSTOM_CHECKS_DIR="$HOME_DIR/lib/python/checks.custom.d"
MACHINE_ID=
TAR_ARCHIVE=
BZIP_ARCHIVE=


progress_flag=0
function progress()
{
    pad=$(printf '%0.1s' "."{1..60})
    line='.......................................................'

    if [ $progress_flag -eq 1 ]; then
        printf " [%s]\n" "$1"
        progress_flag=0
    else
        printf "%s %s" "$1" "${line:${#1}}"
        progress_flag=1
    fi

}


function leave()
{
    if [ $2 -eq 0 ]; then
        echo "$1"
    else
        echo "ERROR: $1"
    fi
    exit $2
}


function verify_files()
{
    progress "Verifying log files title"
    for entry in $LOG_DIR/*.log*; do
        if [ `grep -m 1 -E "[\d\.\,\:\-]+\ +Agent\ starting\ +\(version .+\)" $entry | wc -l` -ne 0 ]; then
            progress "done"
            return
        fi
    done

    leave "No starting log message among the given log files." 1
}


function tarball()
{
    progress "Archiving logs"
    tar -cvf $TAR_ARCHIVE $LOG_DIR/*.log* --transform s,$HOME_DIR_S,$MACHINE_ID, &>/dev/null
    if [ $? -ne 0 ]; then
        progress "failed"
        leave "Cannot execute \`tar\`." 1
    fi
    progress "done"

    progress "Archiving configurations"
    tar -uvf $TAR_ARCHIVE $ETC_DIR/* --transform s,$HOME_DIR_S,$MACHINE_ID, &>/dev/null
    if [ $? -ne 0 ]; then
        progress "failed"
        leave "Cannot execute \`tar\`." 1
    fi
    progress "done"

    progress "Archiving custom checks"
    tar -uvf $TAR_ARCHIVE $CUSTOM_CHECKS_DIR/* --transform s,$HOME_DIR_S,$MACHINE_ID, &>/dev/null
    if [ $? -ne 0 ]; then
        progress "failed"
        leave "Cannot execute \`tar\`." 1
    fi
    progress "done"

    BZIP_ARCHIVE="$TAR_ARCHIVE.bz2"
    progress "Compressing tar archive"
    bzip2 $TAR_ARCHIVE &>/dev/null
    if [ $? -ne 0 ]; then
        progress "failed"
        leave "Cannot execute \`bzip2\`." 1
    fi
    progress "done"
}


progress "Reading current date"
DATE=`date +%Y%m%d%H%m`
if [ $? -ne 0 ]; then
    progress "failed"
    leave "Cannot execute \`date\` command." 1
fi
progress "done"

progress "Checking \`$HOME_DIR\` directory"
if [ ! -d "$HOME_DIR" ]; then
    progress "failed"
    leave "Directory \`$HOME_DIR\` does not exist." 1
fi
progress "done"


progress "Searching for machine ID"
if [[ `grep -i "machine id" -m 1 $LOG_DIR/*.log*` =~ .*machine\ id\:\ *(.*) ]]; then
    MACHINE_ID=${BASH_REMATCH[1]//\:/}
else
    progress "failed"
    leave "Cannot find machine ID in log files" 1
fi
progress "done"

TAR_ARCHIVE=agent-bundle-$MACHINE_ID-$DATE.tar
verify_files
tarball
leave "Log bundle \`$BZIP_ARCHIVE\` created." 0

