#!/bin/bash
set -exu

REPOSITORY_NAME="$1"

# Long interesting tests: pts/sqlite pts/fs-mark pts/iozone pts/dbench pts/pgbench
TESTS="pts/apache pts/nginx pts/postmark pts/phpbench pts/blogbench"

function install_rpm {
	sudo yum -y erase draios-agent draios-tests draios-debug-agent draios-debug-tests

	if ! yum info dkms; then
		sudo rpm -i http://mirror.us.leaseweb.net/epel/6/i386/epel-release-6-8.noarch.rpm # needed for dkms
	fi

	sudo curl -o /etc/yum.repos.d/draios.repo http://download.draios.com/$REPOSITORY_NAME/rpm/draios.repo
	sudo yum -y install kernel-devel-$(uname -r) # this is needed if the customer doesn't have the most updated kernel version
	sudo yum -y install draios-agent draios-tests
}

function install_deb {
	sudo apt-get -y purge draios-agent draios-tests draios-debug-agent draios-debug-tests || true
	sudo curl -o /etc/apt/sources.list.d/draios.list http://download.draios.com/$REPOSITORY_NAME/deb/draios.list
	sudo apt-get update
	sudo apt-get -y install linux-headers-$(uname -r) # this is needed if the customer doesn't have the most updated kernel version
	sudo apt-get -y --force-yes install draios-agent draios-tests
}

if [ -f /etc/debian_version ]; then
    install_deb
    sudo apt-get install php5-cli php5-json php5-gd
elif [ -f /etc/redhat-release ]; then
    install_rpm
elif [ -f /etc/system-release-cpe ]; then
    install_rpm
else
    echo "Unable to detect operating system."
    exit 1
fi

if [ ! -d phoronix-test-suite ]; then
	wget http://phoronix-test-suite.com/releases/phoronix-test-suite-4.8.1.tar.gz
	tar -xzf phoronix-test-suite-4.8.1.tar.gz
fi

cd phoronix-test-suite

if [ ! -d ~/.phoronix-test-suite ]; then	
	echo -e Y\\nY\\nY\\nY\\nN\\nN\\nN\\nN\\nN\\nY | ./phoronix-test-suite batch-setup
fi

rm -rf ~/.phoronix-test-suite/test-results/201*
rm -rf ~/.phoronix-test-suite/test-results/merge
rm -rf /var/crash/*

sudo service dragent stop
sudo service dragent status || true

if [ ! -d ~/.phoronix-test-suite/test-results/no-agent ]; then	
	rm -rf ~/.phoronix-test-suite/test-results
	./phoronix-test-suite batch-benchmark $TESTS
	TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
	echo no-agent | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
	mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/no-agent
fi

sudo modprobe ppm
sudo /opt/draios/bin/scap-open &
./phoronix-test-suite batch-benchmark $TESTS
TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
echo driver-$REPOSITORY_NAME-$TEST_DIR | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/driver-$REPOSITORY_NAME-$TEST_DIR
sudo killall -9 scap-open
sudo rmmod ppm
[ "$(ls /var/crash)" ] && false

sudo service dragent start
./phoronix-test-suite batch-benchmark $TESTS
TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
echo agent-$REPOSITORY_NAME-$TEST_DIR | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/agent-$REPOSITORY_NAME-$TEST_DIR
sudo service dragent status
sudo service dragent stop
[ "$(ls /var/crash)" ] && false

./phoronix-test-suite merge-results $(ls ~/.phoronix-test-suite/test-results)
TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/merge
