#!/bin/bash
set -exu

REPOSITORY_NAME="$1"

# Long interesting tests: pts/sqlite pts/fs-mark pts/iozone pts/dbench pts/pgbench
TESTS="pts/apache pts/nginx pts/postmark pts/phpbench pts/blogbench"

if [ -f /etc/debian_version ]; then
	sudo apt-get -y purge draios-tests draios-debug-agent draios-debug-tests || true
elif [ -f /etc/system-release-cpe ]; then
	sudo yum -y erase draios-tests draios-debug-agent draios-debug-tests
else
    echo "Unable to detect operating system."
    exit 1
fi

curl -s http://download.draios.com/$REPOSITORY_NAME/install-agent | sudo bash -s $REPOSITORY_NAME access_key

if [ -f /etc/debian_version ]; then
	sudo apt-get -y install draios-tests
	sudo apt-get -y install php5-cli php5-json php5-gd
elif [ -f /etc/system-release-cpe ]; then
	sudo yum -y install draios-tests
else
    echo "Unable to detect operating system."
    exit 1
fi

if [ ! -d phoronix-test-suite ]; then
	wget http://www.phoronix-test-suite.com/releases/phoronix-test-suite-4.8.4.tar.gz
	tar -xzf phoronix-test-suite-4.8.4.tar.gz
fi

cd phoronix-test-suite

if [ ! -d ~/.phoronix-test-suite ]; then	
	echo -e Y\\nY\\nY\\nY\\nN\\nN\\nN\\nN\\nN\\nY | ./phoronix-test-suite batch-setup
fi

rm -rf ~/.phoronix-test-suite/test-results/201*
rm -rf ~/.phoronix-test-suite/test-results/merge
sudo rm -rf /var/crash/*

sudo service dragent stop
sudo service dragent status || true

if [ ! -d ~/.phoronix-test-suite/test-results/no-agent ]; then	
	rm -rf ~/.phoronix-test-suite/test-results
	./phoronix-test-suite batch-benchmark $TESTS
	TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
	echo no-agent | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
	mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/no-agent
fi

sudo modprobe ppm
sudo /opt/draios/bin/scap-open &
./phoronix-test-suite batch-benchmark $TESTS
TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
echo driver-$REPOSITORY_NAME-$TEST_DIR | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/driver-$REPOSITORY_NAME-$TEST_DIR
sudo killall -9 scap-open
sudo rmmod ppm
[ "$(ls /var/crash)" ] && false

sudo service dragent start
./phoronix-test-suite batch-benchmark $TESTS
TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
echo agent-$REPOSITORY_NAME-$TEST_DIR | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/agent-$REPOSITORY_NAME-$TEST_DIR
sudo service dragent status
sudo service dragent stop
[ "$(ls /var/crash)" ] && false

./phoronix-test-suite merge-results $(ls ~/.phoronix-test-suite/test-results)
TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)

cd ..
rm -rf merge
mv ~/.phoronix-test-suite/test-results/$TEST_DIR merge
cp -r ~/.phoronix-test-suite/test-results/pts-results-viewer merge/
