#!/bin/bash
set -exu

REPOSITORY_NAME="$1"

function install_rpm {
	if ! yum info dkms; then
		rpm -i http://mirror.us.leaseweb.net/epel/6/i386/epel-release-6-8.noarch.rpm # needed for dkms
	fi

	curl -o /etc/yum.repos.d/draios.repo http://download.draios.com/$REPOSITORY_NAME/rpm/draios.repo
	yum -y install kernel-devel-$(uname -r) # this is needed if the customer doesn't have the most updated kernel version
	yum -y install draios-agent
}

function install_deb {
	curl -o /etc/apt/sources.list.d/draios.list http://download.draios.com/$REPOSITORY_NAME/deb/draios.list
	apt-get update
	apt-get -y install linux-headers-$(uname -r) # this is needed if the customer doesn't have the most updated kernel version
	apt-get -y --force-yes install draios-agent
}

if [ -f /etc/debian_version ]; then
    install_deb
    apt-get install php5-cli php5-json php5-gd
elif [ -f /etc/redhat-release ]; then
    install_rpm
elif [ -f /etc/system-release-cpe ]; then
    install_rpm
else
    echo "Unable to detect operating system."
    exit 1
fi

if [ ! -d phoronix-test-suite ]; then
	wget http://phoronix-test-suite.com/releases/phoronix-test-suite-4.8.1.tar.gz
	tar -xzf phoronix-test-suite-4.8.1.tar.gz
fi

cd phoronix-test-suite

if [ ! -d ~/.phoronix-test-suite ]; then	
	echo -e Y\\nY\\nY\\nY\\nN\\nN\\nN\\nN\\nN\\nY | ./phoronix-test-suite batch-setup
fi

rm -rf ~/.phoronix-test-suite/test-results/201*
rm -rf ~/.phoronix-test-suite/test-results/merge*

if [ ! -d ~/.phoronix-test-suite/test-results/no-agent ]; then	
	rm -rf ~/.phoronix-test-suite/test-results

	service dragent stop
	service dragent status || true

	./phoronix-test-suite batch-benchmark pts/nginx pts/apache
	TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
	echo no-agent | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
	mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/no-agent
fi

service dragent start

./phoronix-test-suite batch-benchmark pts/nginx pts/apache
TEST_DIR=$(ls -t ~/.phoronix-test-suite/test-results | head -1)
echo agent | ./phoronix-test-suite rename-identifier-in-result-file $TEST_DIR
mv ~/.phoronix-test-suite/test-results/$TEST_DIR ~/.phoronix-test-suite/test-results/agent

service dragent status

./phoronix-test-suite merge-results $(ls ~/.phoronix-test-suite/test-results)
