#!/bin/bash
set -exu

rmmod sysdig-probe || true
rm -rf agent/build || true
rm -rf sysdig/build || true
agent/bootstrap-agent
agent/bootstrap-sysdig

make -C agent/build/debug VERBOSE=1
make -C sysdig/build/debug VERBOSE=1
insmod sysdig/driver/sysdig-probe.ko
cd agent/build/debug/test
./test
cd -
cd sysdig/build/debug/userspace/sysdig
./sysdig -n 50
./sysdig -cl
./sysdig -cstdout -n 50
cd -
rmmod sysdig-probe

make -C agent/build/release VERBOSE=1
make -C sysdig/build/release VERBOSE=1
insmod sysdig/driver/sysdig-probe.ko
cd agent/build/release/test
./test
cd -
cd sysdig/build/release/userspace/sysdig
./sysdig -n 50
./sysdig -cl
./sysdig -cstdout -n 50
cd -
rmmod sysdig-probe
