#!/bin/bash
set -exu

rmmod sysdig-probe || true
agent/setup-dependencies

make -C agent/build/debug
make -C sysdig/build/debug
insmod sysdig/driver/sysdig-probe.ko
cd agent/build/debug/test
./test
cd -
cd sysdig/build/debug/userspace/sysdig
./sysdig -n 50
./sysdig -cl
./sysdig -cstdout -n 50
cd -
rmmod sysdig-probe

make -C agent/build/release
make -C sysdig/build/release
insmod sysdig/driver/sysdig-probe.ko
cd agent/build/release/test
./test
cd -
cd sysdig/build/release/userspace/sysdig
./sysdig -n 50
./sysdig -cl
./sysdig -cstdout -n 50
cd -
rmmod sysdig-probe
