#!/bin/bash
set -exu

#
# To be run on CentOS 6
#
export AWS_DEFAULT_REGION="us-east-1"

#
# Update the system
#
yum -y update
reboot

#
# Setup repos 
#
curl -o /etc/yum.repos.d/devtools-2.repo http://people.centos.org/tru/devtools-2/devtools-2.repo
rpm -i http://mirror.pnl.gov/epel/6/i386/epel-release-6-8.noarch.rpm

#
# Install various crap
#
yum -y install \
createrepo \
devtoolset-2-toolchain \
dpkg \
dpkg-devel \
expect \
gcc \
gcc-c++ \
git \
glibc-static \
java-1.7.0-openjdk \
kernel-devel-$(uname -r) \
make \
python-pip \
rpm-build \
unzip \
wget \
cmake28 \
npm

ln -s /usr/bin/cmake28 /usr/bin/cmake

pip install awscli

#
# Needed by rpmsign
#
echo "%_gpg_name Draios Inc. <support@draios.com>" > ~/.rpmmacros

aws s3 cp s3://draios-builder/DRAIOS-GPG-KEY.public .
gpg --import DRAIOS-GPG-KEY.public
rm -f DRAIOS-GPG-KEY.public
aws s3 cp s3://draios-builder/DRAIOS-GPG-KEY.private .
gpg --import DRAIOS-GPG-KEY.private
rm -f DRAIOS-GPG-KEY.private

aws s3 cp s3://draios-builder/config ~/.ssh
aws s3 cp s3://draios-builder/jenkins-github-agent.pem ~/.ssh
aws s3 cp s3://draios-builder/jenkins-github-sysdig.pem ~/.ssh
aws s3 cp s3://draios-builder/jenkins-github-sysdig-private.pem ~/.ssh
chmod 600 ~/.ssh/*

mkfs -t ext4 /dev/xvdf
echo "/dev/xvdf /mnt ext4 defaults,nofail 0 2" >> /etc/fstab
mount -a
