#!/bin/bash
set -exu

#
# To be run on CentOS 6
#

#
# Update the system
#
yum -y update

#
# Setup repos 
#
curl -o /etc/yum.repos.d/devtools-1.1.repo http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo
rpm -i http://mirror.pnl.gov/epel/6/i386/epel-release-6-8.noarch.rpm

#
# Install various crap
#
yum -y install createrepo devtoolset-1.1 dpkg dpkg-devel expect git java-1.7.0-openjdk rpm-build s3cmd unzip wget 

#
# Prepare Jenkins working directory
#
mkdir -p /work/jenkins

#
# Manual steps:
# Copy git key
#
s3cmd --configure
git clone git@github.com:ldegio/draios.git

#
# Needed by rpmsign
#
echo "%_gpg_name Draios Inc. <support@draios.com>" > ~/.rpmmacros

s3cmd get s3://draios-backup/keys/DRAIOS-GPG-KEY.public
gpg --import DRAIOS-GPG-KEY.public
rm -f DRAIOS-GPG-KEY.public
s3cmd get s3://draios-backup/keys/DRAIOS-GPG-KEY.private
gpg --import DRAIOS-GPG-KEY.private
rm -f DRAIOS-GPG-KEY.private
