#!/bin/bash
set -exu

function smoke_tests {
	killall -9 test || true

	# The agent should be running after the installation script	
	sleep 2
	test -e /var/run/dragent.pid
	service dragent status
	MONITOR_PID=$(cat /var/run/dragent.pid)
	AGENT_PID=$(pidof -o $MONITOR_PID dragent)

	# The agent should restart if it dies unexpectedly
	kill -SIGKILL $AGENT_PID
	sleep 2
	pidof -o $MONITOR_PID dragent

	# The restart should work
	service dragent restart
	sleep 2
	MONITOR_PID=$(cat /var/run/dragent.pid)
	pidof -o $MONITOR_PID dragent

	# The stop should work and clean processes and pid files
	service dragent stop
	test ! -e /var/run/dragent.pid
	service dragent status && false
	pidof dragent && false

	# The restart should work even when the agent is not running
	service dragent restart
	sleep 2
	MONITOR_PID=$(cat /var/run/dragent.pid)
	pidof -o $MONITOR_PID dragent
	service dragent stop

	modprobe ppm
	sh -c "cd /opt/draios/test; ./test"
	rmmod ppm
}

function install_rpm {
	yum -y erase draios-tests draios-debug-agent draios-debug-tests
	yum -y install draios-tests
}

function install_deb {
	apt-get -y purge draios-tests draios-debug-agent draios-debug-tests || true
	apt-get -y install draios-tests
}

function install_debug_rpm {
	yum -y erase draios-agent draios-tests draios-debug-agent draios-debug-tests
	yum -y install draios-debug-agent draios-debug-tests
}

function install_debug_deb {
	apt-get -y purge draios-agent draios-tests draios-debug-agent draios-debug-tests || true
	apt-get -y install draios-debug-agent draios-debug-tests
}

if [ -f /etc/debian_version ]; then
    install_deb
elif [ -f /etc/system-release-cpe ]; then
    install_rpm
else
    echo "Unable to detect operating system."
    exit 1
fi

smoke_tests

if [ -f /etc/debian_version ]; then
    install_debug_deb
elif [ -f /etc/system-release-cpe ]; then
    install_debug_rpm
else
    echo "Unable to detect operating system."
    exit 1
fi

service dragent start
smoke_tests
