# This dict describes the fields in each message type which adhere to the built-in
# aggregation scheme. The format is
#
# "message_type" : {raw_field_num:aggregated_field_num}
#
# It is expected that the type of the aggregated field num contains at least weight, max,
# min, and sum.
PRIMARY_KEY = 99999999 #These should probably be an enum. SMAGENT-1976
OR =          99999998
field_extension = {
    "counter_percentile" : {1: PRIMARY_KEY,
                            2:3},
    "counter_time" : {1:4,
                      2:5,
                      3:6},
    "counter_time_bidirectional" : {1:5,
                                    2:6,
                                    3:7,
                                    4:8},
    "counter_bytes" : {1:5,
                       2:6,
                       3:7,
                       4:8},
    "counter_time_bytes" : {1:13,
                            2:14,
                            3:15,
                            4:16,
                            5:17,
                            6:18,
                            7:19,
                            8:20,
                            9:21,
                            10:22,
                            11:23,
                            12:24},
    "counter_syscall_errors" : {1:3,
                                4:7,
                                5:8,
                                6:9},
    "resource_categories" : {1:12,
                             6:7,
                             2:8,
                             3:9,
                             4:10,
                             5:11,
                             13:17,
                             14:18,
                             15:19,
                             16:20,
                             21:22,
                             24:124,
                             25:125,
                             26:126,
                             27:127,
                             28:128,
                             29:129,
                             30:130,
                             31:131,
                             32:132,
                             33:133,
                             34:134,
                             35:135,
                             36:136,
                             37:137,
                             38:138,
                             39:139,
                             40:140,
                             41:141},
    "connection_categories" : {4:5},
    "counter_proto_entry" : {1:7,
                             2:8,
                             3:9,
                             4:10,
                             5:11,
                             6:12},
    "status_code_details" : {2:3},
    "url_details" : {1: PRIMARY_KEY},
    "status_code_details" : {1: PRIMARY_KEY,
                             2:3},
    "sql_entry_details" : {1: PRIMARY_KEY},
    "sql_query_type_details" : {1: PRIMARY_KEY},
    "mongodb_collection_details" : {1: PRIMARY_KEY},
    "mongodb_op_type_details" : {1: PRIMARY_KEY},
    "statsd_tag" : {1: PRIMARY_KEY,
                    2: PRIMARY_KEY},
    "jmx_attribute" : {1: PRIMARY_KEY,
                       2:6}, #SMAGENT-1935
    "jmx_bean" : {1: PRIMARY_KEY},
    "statsd_metric" : {1: PRIMARY_KEY,
                       2: PRIMARY_KEY,
                       4:104,
                       5:105,
                       6:106,
                       7:107,
                       8:108,
                       9:109,
                       10:110,
                       11:111},
    "app_tag" : {1: PRIMARY_KEY},
    "app_metric" : {1: PRIMARY_KEY,
                    3:103,
                    4: PRIMARY_KEY},
    "app_check" : {1: PRIMARY_KEY},
    "network_by_port" : {1: PRIMARY_KEY},
    "host" : {2:21,
              3:15,
              4:17,
              11:16,
              7:18,
              13:20,
              36:136,
              32:132,
              33:133,
              34:134,
              35:135,
              25:125,
              37:137,
              38:138,
              41:141,
              42:142,
              43:143},
    "process_details" : {1: PRIMARY_KEY,
                         2: PRIMARY_KEY,
                         3: PRIMARY_KEY,
                         4: PRIMARY_KEY},
    "process" : {2: PRIMARY_KEY,
                 7:15,
                 12:17,
                 13: OR,
                 21:22,
                 23:123},
    "program" : {1: PRIMARY_KEY,
                 4: PRIMARY_KEY},
    "id_map" : {1: PRIMARY_KEY},
    "environment" : {1: PRIMARY_KEY},
    "ipv4tuple" : {1: PRIMARY_KEY,
                   2: PRIMARY_KEY,
                   3: PRIMARY_KEY,
                   4: PRIMARY_KEY,
                   5: PRIMARY_KEY},
    "ipv4_connection" : {1: PRIMARY_KEY,
                         2: PRIMARY_KEY,
                         5: PRIMARY_KEY},
    "ipv4_incomplete_connection" : {1: PRIMARY_KEY,
                                    2: PRIMARY_KEY},
    "ipv4_network_interface" : {2: PRIMARY_KEY,
                                3: PRIMARY_KEY,
                                4: PRIMARY_KEY},
    "mounted_fs" : {2: PRIMARY_KEY,
                    4:7,
                    5:8,
                    6:9,
                    10:110,
                    11:111},
    "file_stat" : {1: PRIMARY_KEY,
                   2:9,
                   3:6,
                   4:7,
                   5:8},
    "container_port_mapping" : {1: PRIMARY_KEY,
                                2: PRIMARY_KEY,
                                3: PRIMARY_KEY,
                                4: PRIMARY_KEY},
    "container_label" : {1: PRIMARY_KEY,
                         2: PRIMARY_KEY},
    "container" : {1: PRIMARY_KEY,
                   10:15,
                   12:17},
    "mesos_pair" : {1: PRIMARY_KEY},
    "mesos_common" : {1: PRIMARY_KEY},
    "mesos_task" : {1: PRIMARY_KEY},
    "marathon_app" : {1: PRIMARY_KEY},
    "marathon_group" : {1: PRIMARY_KEY},
    "mesos_framework" : {1: PRIMARY_KEY},
    "mesos_slave" : {1: PRIMARY_KEY},
    "swarm_pair" : {1: PRIMARY_KEY,
                    2: PRIMARY_KEY},
    "swarm_common" : {1: PRIMARY_KEY},
    "swarm_port" : {1: PRIMARY_KEY,
                    2: PRIMARY_KEY,
                    3: PRIMARY_KEY},
    "swarm_service" : {1: PRIMARY_KEY,
                       5:7,
                       6:8},
    "swarm_task" : {1: PRIMARY_KEY},
    "swarm_node" : {1: PRIMARY_KEY},
    "swarm_state" : {5:6},
    "key_value" : {1: PRIMARY_KEY, #SMAGENT-1935
                   2: PRIMARY_KEY},
    "agent_event" : {1: PRIMARY_KEY,
                     2: PRIMARY_KEY,
                     3: PRIMARY_KEY,
                     4: PRIMARY_KEY,
                     5: PRIMARY_KEY,
                     6: PRIMARY_KEY}, #SMAGENT-1935
    "metrics" : {10:17},
}

# This set describes types which we will skip. We won't generate any aggregation
# code for messages or fields of this type
skip = set([
    "aggregations64",
    "aggregations64_repeated",
    "aggregations_double"
])

