#!/bin/bash

set -xeuo pipefail

SCRIPT_DIR=$(dirname $(readlink -f $0))
AGENT_SOURCE=$SCRIPT_DIR/../..

# if the previous job failed, there may be dangling images
docker images -q -f 'dangling=true' | xargs --no-run-if-empty docker rmi -f

docker pull quay.io/sysdig/agent-builder:latest
docker tag quay.io/sysdig/agent-builder:latest quay.io/sysdig/agent-builder:prev_latest
docker build -t quay.io/sysdig/agent-builder:latest --pull $AGENT_SOURCE/docker/builder

LATEST_ID=`docker images --format '{{.ID}}' quay.io/sysdig/agent-builder:latest`
PREV_ID=`docker images --format '{{.ID}}' quay.io/sysdig/agent-builder:prev_latest`
if [ -n "$LATEST_ID" -a "$LATEST_ID" != "$PREV_ID" ]; then
	docker push quay.io/sysdig/agent-builder:prev_latest
fi
docker push quay.io/sysdig/agent-builder:latest
docker images -q -f 'dangling=true' | xargs --no-run-if-empty docker rmi -f
