#!/bin/bash

INSTALL_DIR=$1

if [ -n "$INSTALL_DIR" ]
then
	SETUP_CMD="mount --bind $INSTALL_DIR /opt/draios"
else
	SETUP_CMD="true"
fi

shift

TESTS_LOG=`mktemp /tmp/tests.log.XXXXXX`

set +e
unshare -m /bin/bash -c "$SETUP_CMD && cd /opt/draios/test && ./tests $@" 2>&1 | tee $TESTS_LOG
set -e

FAILED_TESTS=$(awk '/ FAILED / && test_list==1 { print $4 } / FAILED.*listed below:/ { test_list=1 }' < $TESTS_LOG | tr \\n :)
rm -f $TESTS_LOG

if [ -n "$FAILED_TESTS" ]
then
	echo "Some tests failed, restarting"
	unshare -m /bin/bash -c "$SETUP_CMD && cd /opt/draios/test && ./tests --gtest_filter=$FAILED_TESTS"
fi
