#!/bin/bash

set -euo pipefail

rm -rf oss-falco
git clone git@github.com:draios/oss-falco.git

cd oss-falco
git remote add upstream git://github.com/falcosecurity/falco.git
git fetch upstream

git pull upstream dev

git push

