#!/usr/bin/env python
from sdchecks import Application

if __name__ == "__main__":
    app = Application()
    try:
    	app.main()
    except KeyboardInterrupt:
    	pass
    finally:
    	app.cleanup()