#!/usr/bin/env python2
import site
site.addsitedir('/opt/draios/lib/python-deps')
import sys
sys.path.append('/opt/draios/lib/python')
from sdchecks import Application

if __name__ == "__main__":
    app = Application()
    try:
    	app.main()
    except KeyboardInterrupt:
    	pass
    finally:
    	app.cleanup()