#!/usr/bin/env python2
# Include our custom path for python libraries
import site
site.addsitedir('/opt/draios/lib/python-deps')
import sys
site.addsitedir('/opt/draios/lib/python-deps%d.%d' % sys.version_info[:2])
sys.path.append('/opt/draios/lib/python')

# Run our app
from sdchecks import Application

if __name__ == "__main__":
    app = Application()
    try:
        app.main()
    except KeyboardInterrupt:
        pass
    finally:
        app.cleanup()