FROM alpine:latest

MAINTAINER Sysdig <support@sysdig.com>

RUN apk add ca-certificates

RUN mkdir -p /opt/draios/bin
ADD agentino /opt/draios/bin/
ADD agentino.debug /debug/agentino.debug

RUN mkdir -p /opt/draios/etc
ADD dragent.default.yaml /opt/draios/etc/

RUN mkdir -p /opt/draios/share
ADD *.lua /opt/draios/share/lua/
RUN mkdir -p /opt/draios/share/lyaml
ADD lyaml/* /opt/draios/share/lua/lyaml/

ADD pdig /opt/draios/bin
ADD libudigembed.so /opt/draios/bin
ADD pdig-debug /opt/draios/bin
ADD libudigembed-debug.so /opt/draios/bin

COPY ./agentino-entrypoint.sh /
ENTRYPOINT ["/agentino-entrypoint.sh"]
