from debian:stable

MAINTAINER Sysdig <support@sysdig.com>

RUN apt-get update -o Acquire::Check-Valid-Until=false \
 && apt-get dist-upgrade -y \
	ca-certificates

ADD draios-0.1.1dev-x86_64-agentino.deb /
RUN dpkg -i /draios-0.1.1dev-x86_64-agentino.deb

COPY ./agentino-entrypoint.sh /
ENTRYPOINT ["/agentino-entrypoint.sh"]
